CREATE TABLE profiles
(
    id                           uuid                     DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    user_id                      uuid,
    created_at                   timestamp with time zone DEFAULT now()             NOT NULL,
    updated_at                   timestamp with time zone DEFAULT now(),
    conversation_id              character varying(255),
    wellbeing_habits             text,
    interests                    text,
    sense_of_humor               text,
    self_care_habits             text,
    money_management             text,
    self_reflection_capabilities text,
    moral_frameworks             text,
    life_goals                   text,
    partnership_values           text,
    spirituality_growth_mindset  text,
    cultural_values              text,
    family_planning              text,
    extroversion_social_energy   double precision,
    routine_vs_spontaneity       double precision,
    agreeableness                double precision,
    conscientiousness            double precision,
    dominance_level              double precision,
    emotional_expressiveness     double precision,
    sex_drive                    double precision,
    geographical_mobility        double precision,
    conflict_resolution_style    character varying(100),
    sexuality_preferences        character varying(100),
    religion                     character varying(100),
    self_portrait                text,
    mutual_commitment            text,
    ideal_date                   text,
    red_green_flags              text,
    neuroticism                  real
);