// Code generated by counterfeiter. DO NOT EDIT.
package youragentfakes

import (
	"context"
	"sync"
	"wingedapp/pgtester/internal/wingedapp/business/domain/youragent"

	"github.com/aarondl/sqlboiler/v4/boil"
)

type FakeUserAIConvoStorer struct {
	InsertUserAIConvoStub        func(context.Context, boil.ContextExecutor, *youragent.InsertUserAIConvo) (*youragent.UserAIConvo, error)
	insertUserAIConvoMutex       sync.RWMutex
	insertUserAIConvoArgsForCall []struct {
		arg1 context.Context
		arg2 boil.ContextExecutor
		arg3 *youragent.InsertUserAIConvo
	}
	insertUserAIConvoReturns struct {
		result1 *youragent.UserAIConvo
		result2 error
	}
	insertUserAIConvoReturnsOnCall map[int]struct {
		result1 *youragent.UserAIConvo
		result2 error
	}
	UserAIConvosStub        func(context.Context, boil.ContextExecutor, *youragent.UserAIConvoQueryFilter) ([]youragent.UserAIConvo, error)
	userAIConvosMutex       sync.RWMutex
	userAIConvosArgsForCall []struct {
		arg1 context.Context
		arg2 boil.ContextExecutor
		arg3 *youragent.UserAIConvoQueryFilter
	}
	userAIConvosReturns struct {
		result1 []youragent.UserAIConvo
		result2 error
	}
	userAIConvosReturnsOnCall map[int]struct {
		result1 []youragent.UserAIConvo
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUserAIConvoStorer) InsertUserAIConvo(arg1 context.Context, arg2 boil.ContextExecutor, arg3 *youragent.InsertUserAIConvo) (*youragent.UserAIConvo, error) {
	fake.insertUserAIConvoMutex.Lock()
	ret, specificReturn := fake.insertUserAIConvoReturnsOnCall[len(fake.insertUserAIConvoArgsForCall)]
	fake.insertUserAIConvoArgsForCall = append(fake.insertUserAIConvoArgsForCall, struct {
		arg1 context.Context
		arg2 boil.ContextExecutor
		arg3 *youragent.InsertUserAIConvo
	}{arg1, arg2, arg3})
	stub := fake.InsertUserAIConvoStub
	fakeReturns := fake.insertUserAIConvoReturns
	fake.recordInvocation("InsertUserAIConvo", []interface{}{arg1, arg2, arg3})
	fake.insertUserAIConvoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserAIConvoStorer) InsertUserAIConvoCallCount() int {
	fake.insertUserAIConvoMutex.RLock()
	defer fake.insertUserAIConvoMutex.RUnlock()
	return len(fake.insertUserAIConvoArgsForCall)
}

func (fake *FakeUserAIConvoStorer) InsertUserAIConvoCalls(stub func(context.Context, boil.ContextExecutor, *youragent.InsertUserAIConvo) (*youragent.UserAIConvo, error)) {
	fake.insertUserAIConvoMutex.Lock()
	defer fake.insertUserAIConvoMutex.Unlock()
	fake.InsertUserAIConvoStub = stub
}

func (fake *FakeUserAIConvoStorer) InsertUserAIConvoArgsForCall(i int) (context.Context, boil.ContextExecutor, *youragent.InsertUserAIConvo) {
	fake.insertUserAIConvoMutex.RLock()
	defer fake.insertUserAIConvoMutex.RUnlock()
	argsForCall := fake.insertUserAIConvoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeUserAIConvoStorer) InsertUserAIConvoReturns(result1 *youragent.UserAIConvo, result2 error) {
	fake.insertUserAIConvoMutex.Lock()
	defer fake.insertUserAIConvoMutex.Unlock()
	fake.InsertUserAIConvoStub = nil
	fake.insertUserAIConvoReturns = struct {
		result1 *youragent.UserAIConvo
		result2 error
	}{result1, result2}
}

func (fake *FakeUserAIConvoStorer) InsertUserAIConvoReturnsOnCall(i int, result1 *youragent.UserAIConvo, result2 error) {
	fake.insertUserAIConvoMutex.Lock()
	defer fake.insertUserAIConvoMutex.Unlock()
	fake.InsertUserAIConvoStub = nil
	if fake.insertUserAIConvoReturnsOnCall == nil {
		fake.insertUserAIConvoReturnsOnCall = make(map[int]struct {
			result1 *youragent.UserAIConvo
			result2 error
		})
	}
	fake.insertUserAIConvoReturnsOnCall[i] = struct {
		result1 *youragent.UserAIConvo
		result2 error
	}{result1, result2}
}

func (fake *FakeUserAIConvoStorer) UserAIConvos(arg1 context.Context, arg2 boil.ContextExecutor, arg3 *youragent.UserAIConvoQueryFilter) ([]youragent.UserAIConvo, error) {
	fake.userAIConvosMutex.Lock()
	ret, specificReturn := fake.userAIConvosReturnsOnCall[len(fake.userAIConvosArgsForCall)]
	fake.userAIConvosArgsForCall = append(fake.userAIConvosArgsForCall, struct {
		arg1 context.Context
		arg2 boil.ContextExecutor
		arg3 *youragent.UserAIConvoQueryFilter
	}{arg1, arg2, arg3})
	stub := fake.UserAIConvosStub
	fakeReturns := fake.userAIConvosReturns
	fake.recordInvocation("UserAIConvos", []interface{}{arg1, arg2, arg3})
	fake.userAIConvosMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserAIConvoStorer) UserAIConvosCallCount() int {
	fake.userAIConvosMutex.RLock()
	defer fake.userAIConvosMutex.RUnlock()
	return len(fake.userAIConvosArgsForCall)
}

func (fake *FakeUserAIConvoStorer) UserAIConvosCalls(stub func(context.Context, boil.ContextExecutor, *youragent.UserAIConvoQueryFilter) ([]youragent.UserAIConvo, error)) {
	fake.userAIConvosMutex.Lock()
	defer fake.userAIConvosMutex.Unlock()
	fake.UserAIConvosStub = stub
}

func (fake *FakeUserAIConvoStorer) UserAIConvosArgsForCall(i int) (context.Context, boil.ContextExecutor, *youragent.UserAIConvoQueryFilter) {
	fake.userAIConvosMutex.RLock()
	defer fake.userAIConvosMutex.RUnlock()
	argsForCall := fake.userAIConvosArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeUserAIConvoStorer) UserAIConvosReturns(result1 []youragent.UserAIConvo, result2 error) {
	fake.userAIConvosMutex.Lock()
	defer fake.userAIConvosMutex.Unlock()
	fake.UserAIConvosStub = nil
	fake.userAIConvosReturns = struct {
		result1 []youragent.UserAIConvo
		result2 error
	}{result1, result2}
}

func (fake *FakeUserAIConvoStorer) UserAIConvosReturnsOnCall(i int, result1 []youragent.UserAIConvo, result2 error) {
	fake.userAIConvosMutex.Lock()
	defer fake.userAIConvosMutex.Unlock()
	fake.UserAIConvosStub = nil
	if fake.userAIConvosReturnsOnCall == nil {
		fake.userAIConvosReturnsOnCall = make(map[int]struct {
			result1 []youragent.UserAIConvo
			result2 error
		})
	}
	fake.userAIConvosReturnsOnCall[i] = struct {
		result1 []youragent.UserAIConvo
		result2 error
	}{result1, result2}
}

func (fake *FakeUserAIConvoStorer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUserAIConvoStorer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
