// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package aipgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Lovestory is an object representing the database table.
type Lovestory struct {
	ID                        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	MatchResultRefID          string      `boil:"match_result_ref_id" json:"match_result_ref_id" toml:"match_result_ref_id" yaml:"match_result_ref_id"`
	UserARefID                string      `boil:"user_a_ref_id" json:"user_a_ref_id" toml:"user_a_ref_id" yaml:"user_a_ref_id"`
	UserBRefID                string      `boil:"user_b_ref_id" json:"user_b_ref_id" toml:"user_b_ref_id" yaml:"user_b_ref_id"`
	FirstDateSimulationScript null.JSON   `boil:"first_date_simulation_script" json:"first_date_simulation_script,omitempty" toml:"first_date_simulation_script" yaml:"first_date_simulation_script,omitempty"`
	FirstDateSimulationAudio  null.String `boil:"first_date_simulation_audio" json:"first_date_simulation_audio,omitempty" toml:"first_date_simulation_audio" yaml:"first_date_simulation_audio,omitempty"`
	Status                    string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt                 time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt                 null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *lovestoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L lovestoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LovestoryColumns = struct {
	ID                        string
	MatchResultRefID          string
	UserARefID                string
	UserBRefID                string
	FirstDateSimulationScript string
	FirstDateSimulationAudio  string
	Status                    string
	CreatedAt                 string
	UpdatedAt                 string
}{
	ID:                        "id",
	MatchResultRefID:          "match_result_ref_id",
	UserARefID:                "user_a_ref_id",
	UserBRefID:                "user_b_ref_id",
	FirstDateSimulationScript: "first_date_simulation_script",
	FirstDateSimulationAudio:  "first_date_simulation_audio",
	Status:                    "status",
	CreatedAt:                 "created_at",
	UpdatedAt:                 "updated_at",
}

var LovestoryTableColumns = struct {
	ID                        string
	MatchResultRefID          string
	UserARefID                string
	UserBRefID                string
	FirstDateSimulationScript string
	FirstDateSimulationAudio  string
	Status                    string
	CreatedAt                 string
	UpdatedAt                 string
}{
	ID:                        "lovestory.id",
	MatchResultRefID:          "lovestory.match_result_ref_id",
	UserARefID:                "lovestory.user_a_ref_id",
	UserBRefID:                "lovestory.user_b_ref_id",
	FirstDateSimulationScript: "lovestory.first_date_simulation_script",
	FirstDateSimulationAudio:  "lovestory.first_date_simulation_audio",
	Status:                    "lovestory.status",
	CreatedAt:                 "lovestory.created_at",
	UpdatedAt:                 "lovestory.updated_at",
}

// Generated where

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var LovestoryWhere = struct {
	ID                        whereHelperstring
	MatchResultRefID          whereHelperstring
	UserARefID                whereHelperstring
	UserBRefID                whereHelperstring
	FirstDateSimulationScript whereHelpernull_JSON
	FirstDateSimulationAudio  whereHelpernull_String
	Status                    whereHelperstring
	CreatedAt                 whereHelpertime_Time
	UpdatedAt                 whereHelpernull_Time
}{
	ID:                        whereHelperstring{field: "\"lovestory\".\"id\""},
	MatchResultRefID:          whereHelperstring{field: "\"lovestory\".\"match_result_ref_id\""},
	UserARefID:                whereHelperstring{field: "\"lovestory\".\"user_a_ref_id\""},
	UserBRefID:                whereHelperstring{field: "\"lovestory\".\"user_b_ref_id\""},
	FirstDateSimulationScript: whereHelpernull_JSON{field: "\"lovestory\".\"first_date_simulation_script\""},
	FirstDateSimulationAudio:  whereHelpernull_String{field: "\"lovestory\".\"first_date_simulation_audio\""},
	Status:                    whereHelperstring{field: "\"lovestory\".\"status\""},
	CreatedAt:                 whereHelpertime_Time{field: "\"lovestory\".\"created_at\""},
	UpdatedAt:                 whereHelpernull_Time{field: "\"lovestory\".\"updated_at\""},
}

// LovestoryRels is where relationship names are stored.
var LovestoryRels = struct {
}{}

// lovestoryR is where relationships are stored.
type lovestoryR struct {
}

// NewStruct creates a new relationship struct
func (*lovestoryR) NewStruct() *lovestoryR {
	return &lovestoryR{}
}

// lovestoryL is where Load methods for each relationship are stored.
type lovestoryL struct{}

var (
	lovestoryAllColumns            = []string{"id", "match_result_ref_id", "user_a_ref_id", "user_b_ref_id", "first_date_simulation_script", "first_date_simulation_audio", "status", "created_at", "updated_at"}
	lovestoryColumnsWithoutDefault = []string{"match_result_ref_id", "user_a_ref_id", "user_b_ref_id"}
	lovestoryColumnsWithDefault    = []string{"id", "first_date_simulation_script", "first_date_simulation_audio", "status", "created_at", "updated_at"}
	lovestoryPrimaryKeyColumns     = []string{"id"}
	lovestoryGeneratedColumns      = []string{}
)

type (
	// LovestorySlice is an alias for a slice of pointers to Lovestory.
	// This should almost always be used instead of []Lovestory.
	LovestorySlice []*Lovestory
	// LovestoryHook is the signature for custom Lovestory hook methods
	LovestoryHook func(context.Context, boil.ContextExecutor, *Lovestory) error

	lovestoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	lovestoryType                 = reflect.TypeOf(&Lovestory{})
	lovestoryMapping              = queries.MakeStructMapping(lovestoryType)
	lovestoryPrimaryKeyMapping, _ = queries.BindMapping(lovestoryType, lovestoryMapping, lovestoryPrimaryKeyColumns)
	lovestoryInsertCacheMut       sync.RWMutex
	lovestoryInsertCache          = make(map[string]insertCache)
	lovestoryUpdateCacheMut       sync.RWMutex
	lovestoryUpdateCache          = make(map[string]updateCache)
	lovestoryUpsertCacheMut       sync.RWMutex
	lovestoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var lovestoryAfterSelectMu sync.Mutex
var lovestoryAfterSelectHooks []LovestoryHook

var lovestoryBeforeInsertMu sync.Mutex
var lovestoryBeforeInsertHooks []LovestoryHook
var lovestoryAfterInsertMu sync.Mutex
var lovestoryAfterInsertHooks []LovestoryHook

var lovestoryBeforeUpdateMu sync.Mutex
var lovestoryBeforeUpdateHooks []LovestoryHook
var lovestoryAfterUpdateMu sync.Mutex
var lovestoryAfterUpdateHooks []LovestoryHook

var lovestoryBeforeDeleteMu sync.Mutex
var lovestoryBeforeDeleteHooks []LovestoryHook
var lovestoryAfterDeleteMu sync.Mutex
var lovestoryAfterDeleteHooks []LovestoryHook

var lovestoryBeforeUpsertMu sync.Mutex
var lovestoryBeforeUpsertHooks []LovestoryHook
var lovestoryAfterUpsertMu sync.Mutex
var lovestoryAfterUpsertHooks []LovestoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Lovestory) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Lovestory) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Lovestory) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Lovestory) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Lovestory) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Lovestory) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Lovestory) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Lovestory) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Lovestory) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range lovestoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddLovestoryHook registers your hook function for all future operations.
func AddLovestoryHook(hookPoint boil.HookPoint, lovestoryHook LovestoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		lovestoryAfterSelectMu.Lock()
		lovestoryAfterSelectHooks = append(lovestoryAfterSelectHooks, lovestoryHook)
		lovestoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		lovestoryBeforeInsertMu.Lock()
		lovestoryBeforeInsertHooks = append(lovestoryBeforeInsertHooks, lovestoryHook)
		lovestoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		lovestoryAfterInsertMu.Lock()
		lovestoryAfterInsertHooks = append(lovestoryAfterInsertHooks, lovestoryHook)
		lovestoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		lovestoryBeforeUpdateMu.Lock()
		lovestoryBeforeUpdateHooks = append(lovestoryBeforeUpdateHooks, lovestoryHook)
		lovestoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		lovestoryAfterUpdateMu.Lock()
		lovestoryAfterUpdateHooks = append(lovestoryAfterUpdateHooks, lovestoryHook)
		lovestoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		lovestoryBeforeDeleteMu.Lock()
		lovestoryBeforeDeleteHooks = append(lovestoryBeforeDeleteHooks, lovestoryHook)
		lovestoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		lovestoryAfterDeleteMu.Lock()
		lovestoryAfterDeleteHooks = append(lovestoryAfterDeleteHooks, lovestoryHook)
		lovestoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		lovestoryBeforeUpsertMu.Lock()
		lovestoryBeforeUpsertHooks = append(lovestoryBeforeUpsertHooks, lovestoryHook)
		lovestoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		lovestoryAfterUpsertMu.Lock()
		lovestoryAfterUpsertHooks = append(lovestoryAfterUpsertHooks, lovestoryHook)
		lovestoryAfterUpsertMu.Unlock()
	}
}

// One returns a single lovestory record from the query.
func (q lovestoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Lovestory, error) {
	o := &Lovestory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "aipgmodel: failed to execute a one query for lovestory")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Lovestory records from the query.
func (q lovestoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (LovestorySlice, error) {
	var o []*Lovestory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "aipgmodel: failed to assign all query results to Lovestory slice")
	}

	if len(lovestoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Lovestory records in the query.
func (q lovestoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to count lovestory rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q lovestoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "aipgmodel: failed to check if lovestory exists")
	}

	return count > 0, nil
}

// Lovestories retrieves all the records using an executor.
func Lovestories(mods ...qm.QueryMod) lovestoryQuery {
	mods = append(mods, qm.From("\"lovestory\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"lovestory\".*"})
	}

	return lovestoryQuery{q}
}

// FindLovestory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLovestory(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Lovestory, error) {
	lovestoryObj := &Lovestory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"lovestory\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, lovestoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "aipgmodel: unable to select from lovestory")
	}

	if err = lovestoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return lovestoryObj, err
	}

	return lovestoryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Lovestory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("aipgmodel: no lovestory provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(lovestoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	lovestoryInsertCacheMut.RLock()
	cache, cached := lovestoryInsertCache[key]
	lovestoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			lovestoryAllColumns,
			lovestoryColumnsWithDefault,
			lovestoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(lovestoryType, lovestoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(lovestoryType, lovestoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"lovestory\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"lovestory\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "aipgmodel: unable to insert into lovestory")
	}

	if !cached {
		lovestoryInsertCacheMut.Lock()
		lovestoryInsertCache[key] = cache
		lovestoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Lovestory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Lovestory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	lovestoryUpdateCacheMut.RLock()
	cache, cached := lovestoryUpdateCache[key]
	lovestoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			lovestoryAllColumns,
			lovestoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("aipgmodel: unable to update lovestory, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"lovestory\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, lovestoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(lovestoryType, lovestoryMapping, append(wl, lovestoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to update lovestory row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by update for lovestory")
	}

	if !cached {
		lovestoryUpdateCacheMut.Lock()
		lovestoryUpdateCache[key] = cache
		lovestoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q lovestoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to update all for lovestory")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to retrieve rows affected for lovestory")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LovestorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("aipgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), lovestoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"lovestory\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, lovestoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to update all in lovestory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to retrieve rows affected all in update all lovestory")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Lovestory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("aipgmodel: no lovestory provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(lovestoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	lovestoryUpsertCacheMut.RLock()
	cache, cached := lovestoryUpsertCache[key]
	lovestoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			lovestoryAllColumns,
			lovestoryColumnsWithDefault,
			lovestoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			lovestoryAllColumns,
			lovestoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("aipgmodel: unable to upsert lovestory, could not build update column list")
		}

		ret := strmangle.SetComplement(lovestoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(lovestoryPrimaryKeyColumns) == 0 {
				return errors.New("aipgmodel: unable to upsert lovestory, could not build conflict column list")
			}

			conflict = make([]string, len(lovestoryPrimaryKeyColumns))
			copy(conflict, lovestoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"lovestory\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(lovestoryType, lovestoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(lovestoryType, lovestoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "aipgmodel: unable to upsert lovestory")
	}

	if !cached {
		lovestoryUpsertCacheMut.Lock()
		lovestoryUpsertCache[key] = cache
		lovestoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Lovestory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Lovestory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("aipgmodel: no Lovestory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), lovestoryPrimaryKeyMapping)
	sql := "DELETE FROM \"lovestory\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to delete from lovestory")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by delete for lovestory")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q lovestoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("aipgmodel: no lovestoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to delete all from lovestory")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by deleteall for lovestory")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LovestorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(lovestoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), lovestoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"lovestory\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, lovestoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to delete all from lovestory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by deleteall for lovestory")
	}

	if len(lovestoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Lovestory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLovestory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LovestorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LovestorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), lovestoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"lovestory\".* FROM \"lovestory\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, lovestoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "aipgmodel: unable to reload all in LovestorySlice")
	}

	*o = slice

	return nil
}

// LovestoryExists checks if the Lovestory row exists.
func LovestoryExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"lovestory\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "aipgmodel: unable to check if lovestory exists")
	}

	return exists, nil
}

// Exists checks if the Lovestory row exists.
func (o *Lovestory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return LovestoryExists(ctx, exec, o.ID)
}
