// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package aipgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Profile is an object representing the database table.
type Profile struct {
	ID                         string       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID                     null.String  `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	CreatedAt                  time.Time    `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt                  null.Time    `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	ConversationID             null.String  `boil:"conversation_id" json:"conversation_id,omitempty" toml:"conversation_id" yaml:"conversation_id,omitempty"`
	WellbeingHabits            null.String  `boil:"wellbeing_habits" json:"wellbeing_habits,omitempty" toml:"wellbeing_habits" yaml:"wellbeing_habits,omitempty"`
	Interests                  null.String  `boil:"interests" json:"interests,omitempty" toml:"interests" yaml:"interests,omitempty"`
	SenseOfHumor               null.String  `boil:"sense_of_humor" json:"sense_of_humor,omitempty" toml:"sense_of_humor" yaml:"sense_of_humor,omitempty"`
	SelfCareHabits             null.String  `boil:"self_care_habits" json:"self_care_habits,omitempty" toml:"self_care_habits" yaml:"self_care_habits,omitempty"`
	MoneyManagement            null.String  `boil:"money_management" json:"money_management,omitempty" toml:"money_management" yaml:"money_management,omitempty"`
	SelfReflectionCapabilities null.String  `boil:"self_reflection_capabilities" json:"self_reflection_capabilities,omitempty" toml:"self_reflection_capabilities" yaml:"self_reflection_capabilities,omitempty"`
	MoralFrameworks            null.String  `boil:"moral_frameworks" json:"moral_frameworks,omitempty" toml:"moral_frameworks" yaml:"moral_frameworks,omitempty"`
	LifeGoals                  null.String  `boil:"life_goals" json:"life_goals,omitempty" toml:"life_goals" yaml:"life_goals,omitempty"`
	PartnershipValues          null.String  `boil:"partnership_values" json:"partnership_values,omitempty" toml:"partnership_values" yaml:"partnership_values,omitempty"`
	SpiritualityGrowthMindset  null.String  `boil:"spirituality_growth_mindset" json:"spirituality_growth_mindset,omitempty" toml:"spirituality_growth_mindset" yaml:"spirituality_growth_mindset,omitempty"`
	CulturalValues             null.String  `boil:"cultural_values" json:"cultural_values,omitempty" toml:"cultural_values" yaml:"cultural_values,omitempty"`
	FamilyPlanning             null.String  `boil:"family_planning" json:"family_planning,omitempty" toml:"family_planning" yaml:"family_planning,omitempty"`
	ExtroversionSocialEnergy   null.Float64 `boil:"extroversion_social_energy" json:"extroversion_social_energy,omitempty" toml:"extroversion_social_energy" yaml:"extroversion_social_energy,omitempty"`
	RoutineVSSpontaneity       null.Float64 `boil:"routine_vs_spontaneity" json:"routine_vs_spontaneity,omitempty" toml:"routine_vs_spontaneity" yaml:"routine_vs_spontaneity,omitempty"`
	Agreeableness              null.Float64 `boil:"agreeableness" json:"agreeableness,omitempty" toml:"agreeableness" yaml:"agreeableness,omitempty"`
	Conscientiousness          null.Float64 `boil:"conscientiousness" json:"conscientiousness,omitempty" toml:"conscientiousness" yaml:"conscientiousness,omitempty"`
	DominanceLevel             null.Float64 `boil:"dominance_level" json:"dominance_level,omitempty" toml:"dominance_level" yaml:"dominance_level,omitempty"`
	EmotionalExpressiveness    null.Float64 `boil:"emotional_expressiveness" json:"emotional_expressiveness,omitempty" toml:"emotional_expressiveness" yaml:"emotional_expressiveness,omitempty"`
	SexDrive                   null.Float64 `boil:"sex_drive" json:"sex_drive,omitempty" toml:"sex_drive" yaml:"sex_drive,omitempty"`
	GeographicalMobility       null.Float64 `boil:"geographical_mobility" json:"geographical_mobility,omitempty" toml:"geographical_mobility" yaml:"geographical_mobility,omitempty"`
	ConflictResolutionStyle    null.String  `boil:"conflict_resolution_style" json:"conflict_resolution_style,omitempty" toml:"conflict_resolution_style" yaml:"conflict_resolution_style,omitempty"`
	SexualityPreferences       null.String  `boil:"sexuality_preferences" json:"sexuality_preferences,omitempty" toml:"sexuality_preferences" yaml:"sexuality_preferences,omitempty"`
	Religion                   null.String  `boil:"religion" json:"religion,omitempty" toml:"religion" yaml:"religion,omitempty"`
	SelfPortrait               null.String  `boil:"self_portrait" json:"self_portrait,omitempty" toml:"self_portrait" yaml:"self_portrait,omitempty"`
	MutualCommitment           null.String  `boil:"mutual_commitment" json:"mutual_commitment,omitempty" toml:"mutual_commitment" yaml:"mutual_commitment,omitempty"`
	IdealDate                  null.String  `boil:"ideal_date" json:"ideal_date,omitempty" toml:"ideal_date" yaml:"ideal_date,omitempty"`
	RedGreenFlags              null.String  `boil:"red_green_flags" json:"red_green_flags,omitempty" toml:"red_green_flags" yaml:"red_green_flags,omitempty"`
	Neuroticism                null.Float32 `boil:"neuroticism" json:"neuroticism,omitempty" toml:"neuroticism" yaml:"neuroticism,omitempty"`

	R *profileR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L profileL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProfileColumns = struct {
	ID                         string
	UserID                     string
	CreatedAt                  string
	UpdatedAt                  string
	ConversationID             string
	WellbeingHabits            string
	Interests                  string
	SenseOfHumor               string
	SelfCareHabits             string
	MoneyManagement            string
	SelfReflectionCapabilities string
	MoralFrameworks            string
	LifeGoals                  string
	PartnershipValues          string
	SpiritualityGrowthMindset  string
	CulturalValues             string
	FamilyPlanning             string
	ExtroversionSocialEnergy   string
	RoutineVSSpontaneity       string
	Agreeableness              string
	Conscientiousness          string
	DominanceLevel             string
	EmotionalExpressiveness    string
	SexDrive                   string
	GeographicalMobility       string
	ConflictResolutionStyle    string
	SexualityPreferences       string
	Religion                   string
	SelfPortrait               string
	MutualCommitment           string
	IdealDate                  string
	RedGreenFlags              string
	Neuroticism                string
}{
	ID:                         "id",
	UserID:                     "user_id",
	CreatedAt:                  "created_at",
	UpdatedAt:                  "updated_at",
	ConversationID:             "conversation_id",
	WellbeingHabits:            "wellbeing_habits",
	Interests:                  "interests",
	SenseOfHumor:               "sense_of_humor",
	SelfCareHabits:             "self_care_habits",
	MoneyManagement:            "money_management",
	SelfReflectionCapabilities: "self_reflection_capabilities",
	MoralFrameworks:            "moral_frameworks",
	LifeGoals:                  "life_goals",
	PartnershipValues:          "partnership_values",
	SpiritualityGrowthMindset:  "spirituality_growth_mindset",
	CulturalValues:             "cultural_values",
	FamilyPlanning:             "family_planning",
	ExtroversionSocialEnergy:   "extroversion_social_energy",
	RoutineVSSpontaneity:       "routine_vs_spontaneity",
	Agreeableness:              "agreeableness",
	Conscientiousness:          "conscientiousness",
	DominanceLevel:             "dominance_level",
	EmotionalExpressiveness:    "emotional_expressiveness",
	SexDrive:                   "sex_drive",
	GeographicalMobility:       "geographical_mobility",
	ConflictResolutionStyle:    "conflict_resolution_style",
	SexualityPreferences:       "sexuality_preferences",
	Religion:                   "religion",
	SelfPortrait:               "self_portrait",
	MutualCommitment:           "mutual_commitment",
	IdealDate:                  "ideal_date",
	RedGreenFlags:              "red_green_flags",
	Neuroticism:                "neuroticism",
}

var ProfileTableColumns = struct {
	ID                         string
	UserID                     string
	CreatedAt                  string
	UpdatedAt                  string
	ConversationID             string
	WellbeingHabits            string
	Interests                  string
	SenseOfHumor               string
	SelfCareHabits             string
	MoneyManagement            string
	SelfReflectionCapabilities string
	MoralFrameworks            string
	LifeGoals                  string
	PartnershipValues          string
	SpiritualityGrowthMindset  string
	CulturalValues             string
	FamilyPlanning             string
	ExtroversionSocialEnergy   string
	RoutineVSSpontaneity       string
	Agreeableness              string
	Conscientiousness          string
	DominanceLevel             string
	EmotionalExpressiveness    string
	SexDrive                   string
	GeographicalMobility       string
	ConflictResolutionStyle    string
	SexualityPreferences       string
	Religion                   string
	SelfPortrait               string
	MutualCommitment           string
	IdealDate                  string
	RedGreenFlags              string
	Neuroticism                string
}{
	ID:                         "profiles.id",
	UserID:                     "profiles.user_id",
	CreatedAt:                  "profiles.created_at",
	UpdatedAt:                  "profiles.updated_at",
	ConversationID:             "profiles.conversation_id",
	WellbeingHabits:            "profiles.wellbeing_habits",
	Interests:                  "profiles.interests",
	SenseOfHumor:               "profiles.sense_of_humor",
	SelfCareHabits:             "profiles.self_care_habits",
	MoneyManagement:            "profiles.money_management",
	SelfReflectionCapabilities: "profiles.self_reflection_capabilities",
	MoralFrameworks:            "profiles.moral_frameworks",
	LifeGoals:                  "profiles.life_goals",
	PartnershipValues:          "profiles.partnership_values",
	SpiritualityGrowthMindset:  "profiles.spirituality_growth_mindset",
	CulturalValues:             "profiles.cultural_values",
	FamilyPlanning:             "profiles.family_planning",
	ExtroversionSocialEnergy:   "profiles.extroversion_social_energy",
	RoutineVSSpontaneity:       "profiles.routine_vs_spontaneity",
	Agreeableness:              "profiles.agreeableness",
	Conscientiousness:          "profiles.conscientiousness",
	DominanceLevel:             "profiles.dominance_level",
	EmotionalExpressiveness:    "profiles.emotional_expressiveness",
	SexDrive:                   "profiles.sex_drive",
	GeographicalMobility:       "profiles.geographical_mobility",
	ConflictResolutionStyle:    "profiles.conflict_resolution_style",
	SexualityPreferences:       "profiles.sexuality_preferences",
	Religion:                   "profiles.religion",
	SelfPortrait:               "profiles.self_portrait",
	MutualCommitment:           "profiles.mutual_commitment",
	IdealDate:                  "profiles.ideal_date",
	RedGreenFlags:              "profiles.red_green_flags",
	Neuroticism:                "profiles.neuroticism",
}

// Generated where

type whereHelpernull_Float32 struct{ field string }

func (w whereHelpernull_Float32) EQ(x null.Float32) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Float32) NEQ(x null.Float32) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Float32) LT(x null.Float32) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Float32) LTE(x null.Float32) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Float32) GT(x null.Float32) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Float32) GTE(x null.Float32) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Float32) IN(slice []float32) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Float32) NIN(slice []float32) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Float32) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Float32) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ProfileWhere = struct {
	ID                         whereHelperstring
	UserID                     whereHelpernull_String
	CreatedAt                  whereHelpertime_Time
	UpdatedAt                  whereHelpernull_Time
	ConversationID             whereHelpernull_String
	WellbeingHabits            whereHelpernull_String
	Interests                  whereHelpernull_String
	SenseOfHumor               whereHelpernull_String
	SelfCareHabits             whereHelpernull_String
	MoneyManagement            whereHelpernull_String
	SelfReflectionCapabilities whereHelpernull_String
	MoralFrameworks            whereHelpernull_String
	LifeGoals                  whereHelpernull_String
	PartnershipValues          whereHelpernull_String
	SpiritualityGrowthMindset  whereHelpernull_String
	CulturalValues             whereHelpernull_String
	FamilyPlanning             whereHelpernull_String
	ExtroversionSocialEnergy   whereHelpernull_Float64
	RoutineVSSpontaneity       whereHelpernull_Float64
	Agreeableness              whereHelpernull_Float64
	Conscientiousness          whereHelpernull_Float64
	DominanceLevel             whereHelpernull_Float64
	EmotionalExpressiveness    whereHelpernull_Float64
	SexDrive                   whereHelpernull_Float64
	GeographicalMobility       whereHelpernull_Float64
	ConflictResolutionStyle    whereHelpernull_String
	SexualityPreferences       whereHelpernull_String
	Religion                   whereHelpernull_String
	SelfPortrait               whereHelpernull_String
	MutualCommitment           whereHelpernull_String
	IdealDate                  whereHelpernull_String
	RedGreenFlags              whereHelpernull_String
	Neuroticism                whereHelpernull_Float32
}{
	ID:                         whereHelperstring{field: "\"profiles\".\"id\""},
	UserID:                     whereHelpernull_String{field: "\"profiles\".\"user_id\""},
	CreatedAt:                  whereHelpertime_Time{field: "\"profiles\".\"created_at\""},
	UpdatedAt:                  whereHelpernull_Time{field: "\"profiles\".\"updated_at\""},
	ConversationID:             whereHelpernull_String{field: "\"profiles\".\"conversation_id\""},
	WellbeingHabits:            whereHelpernull_String{field: "\"profiles\".\"wellbeing_habits\""},
	Interests:                  whereHelpernull_String{field: "\"profiles\".\"interests\""},
	SenseOfHumor:               whereHelpernull_String{field: "\"profiles\".\"sense_of_humor\""},
	SelfCareHabits:             whereHelpernull_String{field: "\"profiles\".\"self_care_habits\""},
	MoneyManagement:            whereHelpernull_String{field: "\"profiles\".\"money_management\""},
	SelfReflectionCapabilities: whereHelpernull_String{field: "\"profiles\".\"self_reflection_capabilities\""},
	MoralFrameworks:            whereHelpernull_String{field: "\"profiles\".\"moral_frameworks\""},
	LifeGoals:                  whereHelpernull_String{field: "\"profiles\".\"life_goals\""},
	PartnershipValues:          whereHelpernull_String{field: "\"profiles\".\"partnership_values\""},
	SpiritualityGrowthMindset:  whereHelpernull_String{field: "\"profiles\".\"spirituality_growth_mindset\""},
	CulturalValues:             whereHelpernull_String{field: "\"profiles\".\"cultural_values\""},
	FamilyPlanning:             whereHelpernull_String{field: "\"profiles\".\"family_planning\""},
	ExtroversionSocialEnergy:   whereHelpernull_Float64{field: "\"profiles\".\"extroversion_social_energy\""},
	RoutineVSSpontaneity:       whereHelpernull_Float64{field: "\"profiles\".\"routine_vs_spontaneity\""},
	Agreeableness:              whereHelpernull_Float64{field: "\"profiles\".\"agreeableness\""},
	Conscientiousness:          whereHelpernull_Float64{field: "\"profiles\".\"conscientiousness\""},
	DominanceLevel:             whereHelpernull_Float64{field: "\"profiles\".\"dominance_level\""},
	EmotionalExpressiveness:    whereHelpernull_Float64{field: "\"profiles\".\"emotional_expressiveness\""},
	SexDrive:                   whereHelpernull_Float64{field: "\"profiles\".\"sex_drive\""},
	GeographicalMobility:       whereHelpernull_Float64{field: "\"profiles\".\"geographical_mobility\""},
	ConflictResolutionStyle:    whereHelpernull_String{field: "\"profiles\".\"conflict_resolution_style\""},
	SexualityPreferences:       whereHelpernull_String{field: "\"profiles\".\"sexuality_preferences\""},
	Religion:                   whereHelpernull_String{field: "\"profiles\".\"religion\""},
	SelfPortrait:               whereHelpernull_String{field: "\"profiles\".\"self_portrait\""},
	MutualCommitment:           whereHelpernull_String{field: "\"profiles\".\"mutual_commitment\""},
	IdealDate:                  whereHelpernull_String{field: "\"profiles\".\"ideal_date\""},
	RedGreenFlags:              whereHelpernull_String{field: "\"profiles\".\"red_green_flags\""},
	Neuroticism:                whereHelpernull_Float32{field: "\"profiles\".\"neuroticism\""},
}

// ProfileRels is where relationship names are stored.
var ProfileRels = struct {
}{}

// profileR is where relationships are stored.
type profileR struct {
}

// NewStruct creates a new relationship struct
func (*profileR) NewStruct() *profileR {
	return &profileR{}
}

// profileL is where Load methods for each relationship are stored.
type profileL struct{}

var (
	profileAllColumns            = []string{"id", "user_id", "created_at", "updated_at", "conversation_id", "wellbeing_habits", "interests", "sense_of_humor", "self_care_habits", "money_management", "self_reflection_capabilities", "moral_frameworks", "life_goals", "partnership_values", "spirituality_growth_mindset", "cultural_values", "family_planning", "extroversion_social_energy", "routine_vs_spontaneity", "agreeableness", "conscientiousness", "dominance_level", "emotional_expressiveness", "sex_drive", "geographical_mobility", "conflict_resolution_style", "sexuality_preferences", "religion", "self_portrait", "mutual_commitment", "ideal_date", "red_green_flags", "neuroticism"}
	profileColumnsWithoutDefault = []string{}
	profileColumnsWithDefault    = []string{"id", "user_id", "created_at", "updated_at", "conversation_id", "wellbeing_habits", "interests", "sense_of_humor", "self_care_habits", "money_management", "self_reflection_capabilities", "moral_frameworks", "life_goals", "partnership_values", "spirituality_growth_mindset", "cultural_values", "family_planning", "extroversion_social_energy", "routine_vs_spontaneity", "agreeableness", "conscientiousness", "dominance_level", "emotional_expressiveness", "sex_drive", "geographical_mobility", "conflict_resolution_style", "sexuality_preferences", "religion", "self_portrait", "mutual_commitment", "ideal_date", "red_green_flags", "neuroticism"}
	profilePrimaryKeyColumns     = []string{"id"}
	profileGeneratedColumns      = []string{}
)

type (
	// ProfileSlice is an alias for a slice of pointers to Profile.
	// This should almost always be used instead of []Profile.
	ProfileSlice []*Profile
	// ProfileHook is the signature for custom Profile hook methods
	ProfileHook func(context.Context, boil.ContextExecutor, *Profile) error

	profileQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	profileType                 = reflect.TypeOf(&Profile{})
	profileMapping              = queries.MakeStructMapping(profileType)
	profilePrimaryKeyMapping, _ = queries.BindMapping(profileType, profileMapping, profilePrimaryKeyColumns)
	profileInsertCacheMut       sync.RWMutex
	profileInsertCache          = make(map[string]insertCache)
	profileUpdateCacheMut       sync.RWMutex
	profileUpdateCache          = make(map[string]updateCache)
	profileUpsertCacheMut       sync.RWMutex
	profileUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var profileAfterSelectMu sync.Mutex
var profileAfterSelectHooks []ProfileHook

var profileBeforeInsertMu sync.Mutex
var profileBeforeInsertHooks []ProfileHook
var profileAfterInsertMu sync.Mutex
var profileAfterInsertHooks []ProfileHook

var profileBeforeUpdateMu sync.Mutex
var profileBeforeUpdateHooks []ProfileHook
var profileAfterUpdateMu sync.Mutex
var profileAfterUpdateHooks []ProfileHook

var profileBeforeDeleteMu sync.Mutex
var profileBeforeDeleteHooks []ProfileHook
var profileAfterDeleteMu sync.Mutex
var profileAfterDeleteHooks []ProfileHook

var profileBeforeUpsertMu sync.Mutex
var profileBeforeUpsertHooks []ProfileHook
var profileAfterUpsertMu sync.Mutex
var profileAfterUpsertHooks []ProfileHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Profile) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Profile) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Profile) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Profile) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Profile) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Profile) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Profile) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Profile) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Profile) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range profileAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProfileHook registers your hook function for all future operations.
func AddProfileHook(hookPoint boil.HookPoint, profileHook ProfileHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		profileAfterSelectMu.Lock()
		profileAfterSelectHooks = append(profileAfterSelectHooks, profileHook)
		profileAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		profileBeforeInsertMu.Lock()
		profileBeforeInsertHooks = append(profileBeforeInsertHooks, profileHook)
		profileBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		profileAfterInsertMu.Lock()
		profileAfterInsertHooks = append(profileAfterInsertHooks, profileHook)
		profileAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		profileBeforeUpdateMu.Lock()
		profileBeforeUpdateHooks = append(profileBeforeUpdateHooks, profileHook)
		profileBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		profileAfterUpdateMu.Lock()
		profileAfterUpdateHooks = append(profileAfterUpdateHooks, profileHook)
		profileAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		profileBeforeDeleteMu.Lock()
		profileBeforeDeleteHooks = append(profileBeforeDeleteHooks, profileHook)
		profileBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		profileAfterDeleteMu.Lock()
		profileAfterDeleteHooks = append(profileAfterDeleteHooks, profileHook)
		profileAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		profileBeforeUpsertMu.Lock()
		profileBeforeUpsertHooks = append(profileBeforeUpsertHooks, profileHook)
		profileBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		profileAfterUpsertMu.Lock()
		profileAfterUpsertHooks = append(profileAfterUpsertHooks, profileHook)
		profileAfterUpsertMu.Unlock()
	}
}

// One returns a single profile record from the query.
func (q profileQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Profile, error) {
	o := &Profile{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "aipgmodel: failed to execute a one query for profiles")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Profile records from the query.
func (q profileQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProfileSlice, error) {
	var o []*Profile

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "aipgmodel: failed to assign all query results to Profile slice")
	}

	if len(profileAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Profile records in the query.
func (q profileQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to count profiles rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q profileQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "aipgmodel: failed to check if profiles exists")
	}

	return count > 0, nil
}

// Profiles retrieves all the records using an executor.
func Profiles(mods ...qm.QueryMod) profileQuery {
	mods = append(mods, qm.From("\"profiles\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"profiles\".*"})
	}

	return profileQuery{q}
}

// FindProfile retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProfile(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Profile, error) {
	profileObj := &Profile{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"profiles\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, profileObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "aipgmodel: unable to select from profiles")
	}

	if err = profileObj.doAfterSelectHooks(ctx, exec); err != nil {
		return profileObj, err
	}

	return profileObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Profile) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("aipgmodel: no profiles provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(profileColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	profileInsertCacheMut.RLock()
	cache, cached := profileInsertCache[key]
	profileInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			profileAllColumns,
			profileColumnsWithDefault,
			profileColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(profileType, profileMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(profileType, profileMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"profiles\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"profiles\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "aipgmodel: unable to insert into profiles")
	}

	if !cached {
		profileInsertCacheMut.Lock()
		profileInsertCache[key] = cache
		profileInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Profile.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Profile) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	profileUpdateCacheMut.RLock()
	cache, cached := profileUpdateCache[key]
	profileUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			profileAllColumns,
			profilePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("aipgmodel: unable to update profiles, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"profiles\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, profilePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(profileType, profileMapping, append(wl, profilePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to update profiles row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by update for profiles")
	}

	if !cached {
		profileUpdateCacheMut.Lock()
		profileUpdateCache[key] = cache
		profileUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q profileQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to update all for profiles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to retrieve rows affected for profiles")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProfileSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("aipgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), profilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"profiles\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, profilePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to update all in profile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to retrieve rows affected all in update all profile")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Profile) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("aipgmodel: no profiles provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(profileColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	profileUpsertCacheMut.RLock()
	cache, cached := profileUpsertCache[key]
	profileUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			profileAllColumns,
			profileColumnsWithDefault,
			profileColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			profileAllColumns,
			profilePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("aipgmodel: unable to upsert profiles, could not build update column list")
		}

		ret := strmangle.SetComplement(profileAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(profilePrimaryKeyColumns) == 0 {
				return errors.New("aipgmodel: unable to upsert profiles, could not build conflict column list")
			}

			conflict = make([]string, len(profilePrimaryKeyColumns))
			copy(conflict, profilePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"profiles\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(profileType, profileMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(profileType, profileMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "aipgmodel: unable to upsert profiles")
	}

	if !cached {
		profileUpsertCacheMut.Lock()
		profileUpsertCache[key] = cache
		profileUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Profile record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Profile) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("aipgmodel: no Profile provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), profilePrimaryKeyMapping)
	sql := "DELETE FROM \"profiles\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to delete from profiles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by delete for profiles")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q profileQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("aipgmodel: no profileQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to delete all from profiles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by deleteall for profiles")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProfileSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(profileBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), profilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"profiles\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, profilePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: unable to delete all from profile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "aipgmodel: failed to get rows affected by deleteall for profiles")
	}

	if len(profileAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Profile) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProfile(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProfileSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProfileSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), profilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"profiles\".* FROM \"profiles\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, profilePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "aipgmodel: unable to reload all in ProfileSlice")
	}

	*o = slice

	return nil
}

// ProfileExists checks if the Profile row exists.
func ProfileExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"profiles\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "aipgmodel: unable to check if profiles exists")
	}

	return exists, nil
}

// Exists checks if the Profile row exists.
func (o *Profile) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ProfileExists(ctx, exec, o.ID)
}
