// Code generated by counterfeiter. DO NOT EDIT.
package matchingfakes

import (
	"context"
	"sync"
	"wingedapp/pgtester/internal/wingedapp/lib/matching"
)

type FakeQualitativeQuantifier struct {
	QualifyStub        func(context.Context, *matching.QualitativeMatchRequest) (*matching.MatchCompatibilityResult, error)
	qualifyMutex       sync.RWMutex
	qualifyArgsForCall []struct {
		arg1 context.Context
		arg2 *matching.QualitativeMatchRequest
	}
	qualifyReturns struct {
		result1 *matching.MatchCompatibilityResult
		result2 error
	}
	qualifyReturnsOnCall map[int]struct {
		result1 *matching.MatchCompatibilityResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeQualitativeQuantifier) Qualify(arg1 context.Context, arg2 *matching.QualitativeMatchRequest) (*matching.MatchCompatibilityResult, error) {
	fake.qualifyMutex.Lock()
	ret, specificReturn := fake.qualifyReturnsOnCall[len(fake.qualifyArgsForCall)]
	fake.qualifyArgsForCall = append(fake.qualifyArgsForCall, struct {
		arg1 context.Context
		arg2 *matching.QualitativeMatchRequest
	}{arg1, arg2})
	stub := fake.QualifyStub
	fakeReturns := fake.qualifyReturns
	fake.recordInvocation("Qualify", []interface{}{arg1, arg2})
	fake.qualifyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeQualitativeQuantifier) QualifyCallCount() int {
	fake.qualifyMutex.RLock()
	defer fake.qualifyMutex.RUnlock()
	return len(fake.qualifyArgsForCall)
}

func (fake *FakeQualitativeQuantifier) QualifyCalls(stub func(context.Context, *matching.QualitativeMatchRequest) (*matching.MatchCompatibilityResult, error)) {
	fake.qualifyMutex.Lock()
	defer fake.qualifyMutex.Unlock()
	fake.QualifyStub = stub
}

func (fake *FakeQualitativeQuantifier) QualifyArgsForCall(i int) (context.Context, *matching.QualitativeMatchRequest) {
	fake.qualifyMutex.RLock()
	defer fake.qualifyMutex.RUnlock()
	argsForCall := fake.qualifyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeQualitativeQuantifier) QualifyReturns(result1 *matching.MatchCompatibilityResult, result2 error) {
	fake.qualifyMutex.Lock()
	defer fake.qualifyMutex.Unlock()
	fake.QualifyStub = nil
	fake.qualifyReturns = struct {
		result1 *matching.MatchCompatibilityResult
		result2 error
	}{result1, result2}
}

func (fake *FakeQualitativeQuantifier) QualifyReturnsOnCall(i int, result1 *matching.MatchCompatibilityResult, result2 error) {
	fake.qualifyMutex.Lock()
	defer fake.qualifyMutex.Unlock()
	fake.QualifyStub = nil
	if fake.qualifyReturnsOnCall == nil {
		fake.qualifyReturnsOnCall = make(map[int]struct {
			result1 *matching.MatchCompatibilityResult
			result2 error
		})
	}
	fake.qualifyReturnsOnCall[i] = struct {
		result1 *matching.MatchCompatibilityResult
		result2 error
	}{result1, result2}
}

func (fake *FakeQualitativeQuantifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeQualitativeQuantifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
