// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AnonymizedContact is an object representing the database table.
type AnonymizedContact struct {
	ID          string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	OwnerHash   string    `boil:"owner_hash" json:"owner_hash" toml:"owner_hash" yaml:"owner_hash"`
	ContactHash string    `boil:"contact_hash" json:"contact_hash" toml:"contact_hash" yaml:"contact_hash"`
	CreatedAt   null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`

	R *anonymizedContactR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L anonymizedContactL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AnonymizedContactColumns = struct {
	ID          string
	OwnerHash   string
	ContactHash string
	CreatedAt   string
}{
	ID:          "id",
	OwnerHash:   "owner_hash",
	ContactHash: "contact_hash",
	CreatedAt:   "created_at",
}

var AnonymizedContactTableColumns = struct {
	ID          string
	OwnerHash   string
	ContactHash string
	CreatedAt   string
}{
	ID:          "anonymized_contact.id",
	OwnerHash:   "anonymized_contact.owner_hash",
	ContactHash: "anonymized_contact.contact_hash",
	CreatedAt:   "anonymized_contact.created_at",
}

// Generated where

var AnonymizedContactWhere = struct {
	ID          whereHelperstring
	OwnerHash   whereHelperstring
	ContactHash whereHelperstring
	CreatedAt   whereHelpernull_Time
}{
	ID:          whereHelperstring{field: "\"anonymized_contact\".\"id\""},
	OwnerHash:   whereHelperstring{field: "\"anonymized_contact\".\"owner_hash\""},
	ContactHash: whereHelperstring{field: "\"anonymized_contact\".\"contact_hash\""},
	CreatedAt:   whereHelpernull_Time{field: "\"anonymized_contact\".\"created_at\""},
}

// AnonymizedContactRels is where relationship names are stored.
var AnonymizedContactRels = struct {
}{}

// anonymizedContactR is where relationships are stored.
type anonymizedContactR struct {
}

// NewStruct creates a new relationship struct
func (*anonymizedContactR) NewStruct() *anonymizedContactR {
	return &anonymizedContactR{}
}

// anonymizedContactL is where Load methods for each relationship are stored.
type anonymizedContactL struct{}

var (
	anonymizedContactAllColumns            = []string{"id", "owner_hash", "contact_hash", "created_at"}
	anonymizedContactColumnsWithoutDefault = []string{"owner_hash", "contact_hash"}
	anonymizedContactColumnsWithDefault    = []string{"id", "created_at"}
	anonymizedContactPrimaryKeyColumns     = []string{"id"}
	anonymizedContactGeneratedColumns      = []string{}
)

type (
	// AnonymizedContactSlice is an alias for a slice of pointers to AnonymizedContact.
	// This should almost always be used instead of []AnonymizedContact.
	AnonymizedContactSlice []*AnonymizedContact
	// AnonymizedContactHook is the signature for custom AnonymizedContact hook methods
	AnonymizedContactHook func(context.Context, boil.ContextExecutor, *AnonymizedContact) error

	anonymizedContactQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	anonymizedContactType                 = reflect.TypeOf(&AnonymizedContact{})
	anonymizedContactMapping              = queries.MakeStructMapping(anonymizedContactType)
	anonymizedContactPrimaryKeyMapping, _ = queries.BindMapping(anonymizedContactType, anonymizedContactMapping, anonymizedContactPrimaryKeyColumns)
	anonymizedContactInsertCacheMut       sync.RWMutex
	anonymizedContactInsertCache          = make(map[string]insertCache)
	anonymizedContactUpdateCacheMut       sync.RWMutex
	anonymizedContactUpdateCache          = make(map[string]updateCache)
	anonymizedContactUpsertCacheMut       sync.RWMutex
	anonymizedContactUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var anonymizedContactAfterSelectMu sync.Mutex
var anonymizedContactAfterSelectHooks []AnonymizedContactHook

var anonymizedContactBeforeInsertMu sync.Mutex
var anonymizedContactBeforeInsertHooks []AnonymizedContactHook
var anonymizedContactAfterInsertMu sync.Mutex
var anonymizedContactAfterInsertHooks []AnonymizedContactHook

var anonymizedContactBeforeUpdateMu sync.Mutex
var anonymizedContactBeforeUpdateHooks []AnonymizedContactHook
var anonymizedContactAfterUpdateMu sync.Mutex
var anonymizedContactAfterUpdateHooks []AnonymizedContactHook

var anonymizedContactBeforeDeleteMu sync.Mutex
var anonymizedContactBeforeDeleteHooks []AnonymizedContactHook
var anonymizedContactAfterDeleteMu sync.Mutex
var anonymizedContactAfterDeleteHooks []AnonymizedContactHook

var anonymizedContactBeforeUpsertMu sync.Mutex
var anonymizedContactBeforeUpsertHooks []AnonymizedContactHook
var anonymizedContactAfterUpsertMu sync.Mutex
var anonymizedContactAfterUpsertHooks []AnonymizedContactHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AnonymizedContact) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AnonymizedContact) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AnonymizedContact) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AnonymizedContact) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AnonymizedContact) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AnonymizedContact) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AnonymizedContact) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AnonymizedContact) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AnonymizedContact) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range anonymizedContactAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAnonymizedContactHook registers your hook function for all future operations.
func AddAnonymizedContactHook(hookPoint boil.HookPoint, anonymizedContactHook AnonymizedContactHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		anonymizedContactAfterSelectMu.Lock()
		anonymizedContactAfterSelectHooks = append(anonymizedContactAfterSelectHooks, anonymizedContactHook)
		anonymizedContactAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		anonymizedContactBeforeInsertMu.Lock()
		anonymizedContactBeforeInsertHooks = append(anonymizedContactBeforeInsertHooks, anonymizedContactHook)
		anonymizedContactBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		anonymizedContactAfterInsertMu.Lock()
		anonymizedContactAfterInsertHooks = append(anonymizedContactAfterInsertHooks, anonymizedContactHook)
		anonymizedContactAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		anonymizedContactBeforeUpdateMu.Lock()
		anonymizedContactBeforeUpdateHooks = append(anonymizedContactBeforeUpdateHooks, anonymizedContactHook)
		anonymizedContactBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		anonymizedContactAfterUpdateMu.Lock()
		anonymizedContactAfterUpdateHooks = append(anonymizedContactAfterUpdateHooks, anonymizedContactHook)
		anonymizedContactAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		anonymizedContactBeforeDeleteMu.Lock()
		anonymizedContactBeforeDeleteHooks = append(anonymizedContactBeforeDeleteHooks, anonymizedContactHook)
		anonymizedContactBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		anonymizedContactAfterDeleteMu.Lock()
		anonymizedContactAfterDeleteHooks = append(anonymizedContactAfterDeleteHooks, anonymizedContactHook)
		anonymizedContactAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		anonymizedContactBeforeUpsertMu.Lock()
		anonymizedContactBeforeUpsertHooks = append(anonymizedContactBeforeUpsertHooks, anonymizedContactHook)
		anonymizedContactBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		anonymizedContactAfterUpsertMu.Lock()
		anonymizedContactAfterUpsertHooks = append(anonymizedContactAfterUpsertHooks, anonymizedContactHook)
		anonymizedContactAfterUpsertMu.Unlock()
	}
}

// One returns a single anonymizedContact record from the query.
func (q anonymizedContactQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AnonymizedContact, error) {
	o := &AnonymizedContact{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for anonymized_contact")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AnonymizedContact records from the query.
func (q anonymizedContactQuery) All(ctx context.Context, exec boil.ContextExecutor) (AnonymizedContactSlice, error) {
	var o []*AnonymizedContact

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to AnonymizedContact slice")
	}

	if len(anonymizedContactAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AnonymizedContact records in the query.
func (q anonymizedContactQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count anonymized_contact rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q anonymizedContactQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if anonymized_contact exists")
	}

	return count > 0, nil
}

// AnonymizedContacts retrieves all the records using an executor.
func AnonymizedContacts(mods ...qm.QueryMod) anonymizedContactQuery {
	mods = append(mods, qm.From("\"anonymized_contact\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"anonymized_contact\".*"})
	}

	return anonymizedContactQuery{q}
}

// FindAnonymizedContact retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAnonymizedContact(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AnonymizedContact, error) {
	anonymizedContactObj := &AnonymizedContact{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"anonymized_contact\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, anonymizedContactObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from anonymized_contact")
	}

	if err = anonymizedContactObj.doAfterSelectHooks(ctx, exec); err != nil {
		return anonymizedContactObj, err
	}

	return anonymizedContactObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AnonymizedContact) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no anonymized_contact provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(anonymizedContactColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	anonymizedContactInsertCacheMut.RLock()
	cache, cached := anonymizedContactInsertCache[key]
	anonymizedContactInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			anonymizedContactAllColumns,
			anonymizedContactColumnsWithDefault,
			anonymizedContactColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(anonymizedContactType, anonymizedContactMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(anonymizedContactType, anonymizedContactMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"anonymized_contact\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"anonymized_contact\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into anonymized_contact")
	}

	if !cached {
		anonymizedContactInsertCacheMut.Lock()
		anonymizedContactInsertCache[key] = cache
		anonymizedContactInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AnonymizedContact.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AnonymizedContact) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	anonymizedContactUpdateCacheMut.RLock()
	cache, cached := anonymizedContactUpdateCache[key]
	anonymizedContactUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			anonymizedContactAllColumns,
			anonymizedContactPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update anonymized_contact, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"anonymized_contact\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, anonymizedContactPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(anonymizedContactType, anonymizedContactMapping, append(wl, anonymizedContactPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update anonymized_contact row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for anonymized_contact")
	}

	if !cached {
		anonymizedContactUpdateCacheMut.Lock()
		anonymizedContactUpdateCache[key] = cache
		anonymizedContactUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q anonymizedContactQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for anonymized_contact")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for anonymized_contact")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AnonymizedContactSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), anonymizedContactPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"anonymized_contact\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, anonymizedContactPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in anonymizedContact slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all anonymizedContact")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AnonymizedContact) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no anonymized_contact provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(anonymizedContactColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	anonymizedContactUpsertCacheMut.RLock()
	cache, cached := anonymizedContactUpsertCache[key]
	anonymizedContactUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			anonymizedContactAllColumns,
			anonymizedContactColumnsWithDefault,
			anonymizedContactColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			anonymizedContactAllColumns,
			anonymizedContactPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert anonymized_contact, could not build update column list")
		}

		ret := strmangle.SetComplement(anonymizedContactAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(anonymizedContactPrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert anonymized_contact, could not build conflict column list")
			}

			conflict = make([]string, len(anonymizedContactPrimaryKeyColumns))
			copy(conflict, anonymizedContactPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"anonymized_contact\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(anonymizedContactType, anonymizedContactMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(anonymizedContactType, anonymizedContactMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert anonymized_contact")
	}

	if !cached {
		anonymizedContactUpsertCacheMut.Lock()
		anonymizedContactUpsertCache[key] = cache
		anonymizedContactUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AnonymizedContact record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AnonymizedContact) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no AnonymizedContact provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), anonymizedContactPrimaryKeyMapping)
	sql := "DELETE FROM \"anonymized_contact\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from anonymized_contact")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for anonymized_contact")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q anonymizedContactQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no anonymizedContactQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from anonymized_contact")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for anonymized_contact")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AnonymizedContactSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(anonymizedContactBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), anonymizedContactPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"anonymized_contact\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, anonymizedContactPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from anonymizedContact slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for anonymized_contact")
	}

	if len(anonymizedContactAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AnonymizedContact) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAnonymizedContact(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AnonymizedContactSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AnonymizedContactSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), anonymizedContactPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"anonymized_contact\".* FROM \"anonymized_contact\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, anonymizedContactPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in AnonymizedContactSlice")
	}

	*o = slice

	return nil
}

// AnonymizedContactExists checks if the AnonymizedContact row exists.
func AnonymizedContactExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"anonymized_contact\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if anonymized_contact exists")
	}

	return exists, nil
}

// Exists checks if the AnonymizedContact row exists.
func (o *AnonymizedContact) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AnonymizedContactExists(ctx, exec, o.ID)
}
