// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// BookingReminder is an object representing the database table.
type BookingReminder struct {
	ID                string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	DateInstanceRefID string    `boil:"date_instance_ref_id" json:"date_instance_ref_id" toml:"date_instance_ref_id" yaml:"date_instance_ref_id"`
	Status            string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	RemindAt          time.Time `boil:"remind_at" json:"remind_at" toml:"remind_at" yaml:"remind_at"`
	CreatedAt         time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	FiredAt           null.Time `boil:"fired_at" json:"fired_at,omitempty" toml:"fired_at" yaml:"fired_at,omitempty"`

	R *bookingReminderR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bookingReminderL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BookingReminderColumns = struct {
	ID                string
	DateInstanceRefID string
	Status            string
	RemindAt          string
	CreatedAt         string
	FiredAt           string
}{
	ID:                "id",
	DateInstanceRefID: "date_instance_ref_id",
	Status:            "status",
	RemindAt:          "remind_at",
	CreatedAt:         "created_at",
	FiredAt:           "fired_at",
}

var BookingReminderTableColumns = struct {
	ID                string
	DateInstanceRefID string
	Status            string
	RemindAt          string
	CreatedAt         string
	FiredAt           string
}{
	ID:                "booking_reminder.id",
	DateInstanceRefID: "booking_reminder.date_instance_ref_id",
	Status:            "booking_reminder.status",
	RemindAt:          "booking_reminder.remind_at",
	CreatedAt:         "booking_reminder.created_at",
	FiredAt:           "booking_reminder.fired_at",
}

// Generated where

var BookingReminderWhere = struct {
	ID                whereHelperstring
	DateInstanceRefID whereHelperstring
	Status            whereHelperstring
	RemindAt          whereHelpertime_Time
	CreatedAt         whereHelpertime_Time
	FiredAt           whereHelpernull_Time
}{
	ID:                whereHelperstring{field: "\"booking_reminder\".\"id\""},
	DateInstanceRefID: whereHelperstring{field: "\"booking_reminder\".\"date_instance_ref_id\""},
	Status:            whereHelperstring{field: "\"booking_reminder\".\"status\""},
	RemindAt:          whereHelpertime_Time{field: "\"booking_reminder\".\"remind_at\""},
	CreatedAt:         whereHelpertime_Time{field: "\"booking_reminder\".\"created_at\""},
	FiredAt:           whereHelpernull_Time{field: "\"booking_reminder\".\"fired_at\""},
}

// BookingReminderRels is where relationship names are stored.
var BookingReminderRels = struct {
	DateInstanceRef string
}{
	DateInstanceRef: "DateInstanceRef",
}

// bookingReminderR is where relationships are stored.
type bookingReminderR struct {
	DateInstanceRef *DateInstance `boil:"DateInstanceRef" json:"DateInstanceRef" toml:"DateInstanceRef" yaml:"DateInstanceRef"`
}

// NewStruct creates a new relationship struct
func (*bookingReminderR) NewStruct() *bookingReminderR {
	return &bookingReminderR{}
}

func (o *BookingReminder) GetDateInstanceRef() *DateInstance {
	if o == nil {
		return nil
	}

	return o.R.GetDateInstanceRef()
}

func (r *bookingReminderR) GetDateInstanceRef() *DateInstance {
	if r == nil {
		return nil
	}

	return r.DateInstanceRef
}

// bookingReminderL is where Load methods for each relationship are stored.
type bookingReminderL struct{}

var (
	bookingReminderAllColumns            = []string{"id", "date_instance_ref_id", "status", "remind_at", "created_at", "fired_at"}
	bookingReminderColumnsWithoutDefault = []string{"date_instance_ref_id", "remind_at"}
	bookingReminderColumnsWithDefault    = []string{"id", "status", "created_at", "fired_at"}
	bookingReminderPrimaryKeyColumns     = []string{"id"}
	bookingReminderGeneratedColumns      = []string{}
)

type (
	// BookingReminderSlice is an alias for a slice of pointers to BookingReminder.
	// This should almost always be used instead of []BookingReminder.
	BookingReminderSlice []*BookingReminder
	// BookingReminderHook is the signature for custom BookingReminder hook methods
	BookingReminderHook func(context.Context, boil.ContextExecutor, *BookingReminder) error

	bookingReminderQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bookingReminderType                 = reflect.TypeOf(&BookingReminder{})
	bookingReminderMapping              = queries.MakeStructMapping(bookingReminderType)
	bookingReminderPrimaryKeyMapping, _ = queries.BindMapping(bookingReminderType, bookingReminderMapping, bookingReminderPrimaryKeyColumns)
	bookingReminderInsertCacheMut       sync.RWMutex
	bookingReminderInsertCache          = make(map[string]insertCache)
	bookingReminderUpdateCacheMut       sync.RWMutex
	bookingReminderUpdateCache          = make(map[string]updateCache)
	bookingReminderUpsertCacheMut       sync.RWMutex
	bookingReminderUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var bookingReminderAfterSelectMu sync.Mutex
var bookingReminderAfterSelectHooks []BookingReminderHook

var bookingReminderBeforeInsertMu sync.Mutex
var bookingReminderBeforeInsertHooks []BookingReminderHook
var bookingReminderAfterInsertMu sync.Mutex
var bookingReminderAfterInsertHooks []BookingReminderHook

var bookingReminderBeforeUpdateMu sync.Mutex
var bookingReminderBeforeUpdateHooks []BookingReminderHook
var bookingReminderAfterUpdateMu sync.Mutex
var bookingReminderAfterUpdateHooks []BookingReminderHook

var bookingReminderBeforeDeleteMu sync.Mutex
var bookingReminderBeforeDeleteHooks []BookingReminderHook
var bookingReminderAfterDeleteMu sync.Mutex
var bookingReminderAfterDeleteHooks []BookingReminderHook

var bookingReminderBeforeUpsertMu sync.Mutex
var bookingReminderBeforeUpsertHooks []BookingReminderHook
var bookingReminderAfterUpsertMu sync.Mutex
var bookingReminderAfterUpsertHooks []BookingReminderHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BookingReminder) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BookingReminder) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BookingReminder) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BookingReminder) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BookingReminder) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BookingReminder) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BookingReminder) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BookingReminder) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BookingReminder) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingReminderAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBookingReminderHook registers your hook function for all future operations.
func AddBookingReminderHook(hookPoint boil.HookPoint, bookingReminderHook BookingReminderHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		bookingReminderAfterSelectMu.Lock()
		bookingReminderAfterSelectHooks = append(bookingReminderAfterSelectHooks, bookingReminderHook)
		bookingReminderAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		bookingReminderBeforeInsertMu.Lock()
		bookingReminderBeforeInsertHooks = append(bookingReminderBeforeInsertHooks, bookingReminderHook)
		bookingReminderBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		bookingReminderAfterInsertMu.Lock()
		bookingReminderAfterInsertHooks = append(bookingReminderAfterInsertHooks, bookingReminderHook)
		bookingReminderAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		bookingReminderBeforeUpdateMu.Lock()
		bookingReminderBeforeUpdateHooks = append(bookingReminderBeforeUpdateHooks, bookingReminderHook)
		bookingReminderBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		bookingReminderAfterUpdateMu.Lock()
		bookingReminderAfterUpdateHooks = append(bookingReminderAfterUpdateHooks, bookingReminderHook)
		bookingReminderAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		bookingReminderBeforeDeleteMu.Lock()
		bookingReminderBeforeDeleteHooks = append(bookingReminderBeforeDeleteHooks, bookingReminderHook)
		bookingReminderBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		bookingReminderAfterDeleteMu.Lock()
		bookingReminderAfterDeleteHooks = append(bookingReminderAfterDeleteHooks, bookingReminderHook)
		bookingReminderAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		bookingReminderBeforeUpsertMu.Lock()
		bookingReminderBeforeUpsertHooks = append(bookingReminderBeforeUpsertHooks, bookingReminderHook)
		bookingReminderBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		bookingReminderAfterUpsertMu.Lock()
		bookingReminderAfterUpsertHooks = append(bookingReminderAfterUpsertHooks, bookingReminderHook)
		bookingReminderAfterUpsertMu.Unlock()
	}
}

// One returns a single bookingReminder record from the query.
func (q bookingReminderQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BookingReminder, error) {
	o := &BookingReminder{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for booking_reminder")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all BookingReminder records from the query.
func (q bookingReminderQuery) All(ctx context.Context, exec boil.ContextExecutor) (BookingReminderSlice, error) {
	var o []*BookingReminder

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to BookingReminder slice")
	}

	if len(bookingReminderAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all BookingReminder records in the query.
func (q bookingReminderQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count booking_reminder rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q bookingReminderQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if booking_reminder exists")
	}

	return count > 0, nil
}

// DateInstanceRef pointed to by the foreign key.
func (o *BookingReminder) DateInstanceRef(mods ...qm.QueryMod) dateInstanceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DateInstanceRefID),
	}

	queryMods = append(queryMods, mods...)

	return DateInstances(queryMods...)
}

// LoadDateInstanceRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (bookingReminderL) LoadDateInstanceRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBookingReminder interface{}, mods queries.Applicator) error {
	var slice []*BookingReminder
	var object *BookingReminder

	if singular {
		var ok bool
		object, ok = maybeBookingReminder.(*BookingReminder)
		if !ok {
			object = new(BookingReminder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBookingReminder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBookingReminder))
			}
		}
	} else {
		s, ok := maybeBookingReminder.(*[]*BookingReminder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBookingReminder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBookingReminder))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bookingReminderR{}
		}
		args[object.DateInstanceRefID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bookingReminderR{}
			}

			args[obj.DateInstanceRefID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`date_instance`),
		qm.WhereIn(`date_instance.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DateInstance")
	}

	var resultSlice []*DateInstance
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DateInstance")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for date_instance")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for date_instance")
	}

	if len(dateInstanceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DateInstanceRef = foreign
		if foreign.R == nil {
			foreign.R = &dateInstanceR{}
		}
		foreign.R.DateInstanceRefBookingReminders = append(foreign.R.DateInstanceRefBookingReminders, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DateInstanceRefID == foreign.ID {
				local.R.DateInstanceRef = foreign
				if foreign.R == nil {
					foreign.R = &dateInstanceR{}
				}
				foreign.R.DateInstanceRefBookingReminders = append(foreign.R.DateInstanceRefBookingReminders, local)
				break
			}
		}
	}

	return nil
}

// SetDateInstanceRef of the bookingReminder to the related item.
// Sets o.R.DateInstanceRef to related.
// Adds o to related.R.DateInstanceRefBookingReminders.
func (o *BookingReminder) SetDateInstanceRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DateInstance) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"booking_reminder\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"date_instance_ref_id"}),
		strmangle.WhereClause("\"", "\"", 2, bookingReminderPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DateInstanceRefID = related.ID
	if o.R == nil {
		o.R = &bookingReminderR{
			DateInstanceRef: related,
		}
	} else {
		o.R.DateInstanceRef = related
	}

	if related.R == nil {
		related.R = &dateInstanceR{
			DateInstanceRefBookingReminders: BookingReminderSlice{o},
		}
	} else {
		related.R.DateInstanceRefBookingReminders = append(related.R.DateInstanceRefBookingReminders, o)
	}

	return nil
}

// BookingReminders retrieves all the records using an executor.
func BookingReminders(mods ...qm.QueryMod) bookingReminderQuery {
	mods = append(mods, qm.From("\"booking_reminder\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"booking_reminder\".*"})
	}

	return bookingReminderQuery{q}
}

// FindBookingReminder retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBookingReminder(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*BookingReminder, error) {
	bookingReminderObj := &BookingReminder{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"booking_reminder\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, bookingReminderObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from booking_reminder")
	}

	if err = bookingReminderObj.doAfterSelectHooks(ctx, exec); err != nil {
		return bookingReminderObj, err
	}

	return bookingReminderObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BookingReminder) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no booking_reminder provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bookingReminderColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	bookingReminderInsertCacheMut.RLock()
	cache, cached := bookingReminderInsertCache[key]
	bookingReminderInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			bookingReminderAllColumns,
			bookingReminderColumnsWithDefault,
			bookingReminderColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(bookingReminderType, bookingReminderMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bookingReminderType, bookingReminderMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"booking_reminder\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"booking_reminder\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into booking_reminder")
	}

	if !cached {
		bookingReminderInsertCacheMut.Lock()
		bookingReminderInsertCache[key] = cache
		bookingReminderInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the BookingReminder.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BookingReminder) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	bookingReminderUpdateCacheMut.RLock()
	cache, cached := bookingReminderUpdateCache[key]
	bookingReminderUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			bookingReminderAllColumns,
			bookingReminderPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update booking_reminder, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"booking_reminder\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, bookingReminderPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bookingReminderType, bookingReminderMapping, append(wl, bookingReminderPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update booking_reminder row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for booking_reminder")
	}

	if !cached {
		bookingReminderUpdateCacheMut.Lock()
		bookingReminderUpdateCache[key] = cache
		bookingReminderUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q bookingReminderQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for booking_reminder")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for booking_reminder")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BookingReminderSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingReminderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"booking_reminder\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, bookingReminderPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in bookingReminder slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all bookingReminder")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BookingReminder) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no booking_reminder provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bookingReminderColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bookingReminderUpsertCacheMut.RLock()
	cache, cached := bookingReminderUpsertCache[key]
	bookingReminderUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			bookingReminderAllColumns,
			bookingReminderColumnsWithDefault,
			bookingReminderColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			bookingReminderAllColumns,
			bookingReminderPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert booking_reminder, could not build update column list")
		}

		ret := strmangle.SetComplement(bookingReminderAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(bookingReminderPrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert booking_reminder, could not build conflict column list")
			}

			conflict = make([]string, len(bookingReminderPrimaryKeyColumns))
			copy(conflict, bookingReminderPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"booking_reminder\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(bookingReminderType, bookingReminderMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bookingReminderType, bookingReminderMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert booking_reminder")
	}

	if !cached {
		bookingReminderUpsertCacheMut.Lock()
		bookingReminderUpsertCache[key] = cache
		bookingReminderUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single BookingReminder record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BookingReminder) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no BookingReminder provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bookingReminderPrimaryKeyMapping)
	sql := "DELETE FROM \"booking_reminder\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from booking_reminder")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for booking_reminder")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q bookingReminderQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no bookingReminderQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from booking_reminder")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for booking_reminder")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BookingReminderSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(bookingReminderBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingReminderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"booking_reminder\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookingReminderPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from bookingReminder slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for booking_reminder")
	}

	if len(bookingReminderAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BookingReminder) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBookingReminder(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BookingReminderSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BookingReminderSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingReminderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"booking_reminder\".* FROM \"booking_reminder\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookingReminderPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in BookingReminderSlice")
	}

	*o = slice

	return nil
}

// BookingReminderExists checks if the BookingReminder row exists.
func BookingReminderExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"booking_reminder\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if booking_reminder exists")
	}

	return exists, nil
}

// Exists checks if the BookingReminder row exists.
func (o *BookingReminder) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BookingReminderExists(ctx, exec, o.ID)
}
