// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DateInstanceProposal is an object representing the database table.
type DateInstanceProposal struct {
	ID                string `boil:"id" json:"id" toml:"id" yaml:"id"`
	DateInstanceRefID string `boil:"date_instance_ref_id" json:"date_instance_ref_id" toml:"date_instance_ref_id" yaml:"date_instance_ref_id"`
	SuggestedByRefID  string `boil:"suggested_by_ref_id" json:"suggested_by_ref_id" toml:"suggested_by_ref_id" yaml:"suggested_by_ref_id"`
	// The proposed date/time in UTC. Must be in the future when created.
	ProposedTime time.Time `boil:"proposed_time" json:"proposed_time" toml:"proposed_time" yaml:"proposed_time"`
	// pending=awaiting selection, accepted=chosen by initiator, rejected=not chosen, superseded=replaced by new proposals
	Status    string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *dateInstanceProposalR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dateInstanceProposalL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DateInstanceProposalColumns = struct {
	ID                string
	DateInstanceRefID string
	SuggestedByRefID  string
	ProposedTime      string
	Status            string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "id",
	DateInstanceRefID: "date_instance_ref_id",
	SuggestedByRefID:  "suggested_by_ref_id",
	ProposedTime:      "proposed_time",
	Status:            "status",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

var DateInstanceProposalTableColumns = struct {
	ID                string
	DateInstanceRefID string
	SuggestedByRefID  string
	ProposedTime      string
	Status            string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "date_instance_proposal.id",
	DateInstanceRefID: "date_instance_proposal.date_instance_ref_id",
	SuggestedByRefID:  "date_instance_proposal.suggested_by_ref_id",
	ProposedTime:      "date_instance_proposal.proposed_time",
	Status:            "date_instance_proposal.status",
	CreatedAt:         "date_instance_proposal.created_at",
	UpdatedAt:         "date_instance_proposal.updated_at",
}

// Generated where

var DateInstanceProposalWhere = struct {
	ID                whereHelperstring
	DateInstanceRefID whereHelperstring
	SuggestedByRefID  whereHelperstring
	ProposedTime      whereHelpertime_Time
	Status            whereHelperstring
	CreatedAt         whereHelpertime_Time
	UpdatedAt         whereHelpernull_Time
}{
	ID:                whereHelperstring{field: "\"date_instance_proposal\".\"id\""},
	DateInstanceRefID: whereHelperstring{field: "\"date_instance_proposal\".\"date_instance_ref_id\""},
	SuggestedByRefID:  whereHelperstring{field: "\"date_instance_proposal\".\"suggested_by_ref_id\""},
	ProposedTime:      whereHelpertime_Time{field: "\"date_instance_proposal\".\"proposed_time\""},
	Status:            whereHelperstring{field: "\"date_instance_proposal\".\"status\""},
	CreatedAt:         whereHelpertime_Time{field: "\"date_instance_proposal\".\"created_at\""},
	UpdatedAt:         whereHelpernull_Time{field: "\"date_instance_proposal\".\"updated_at\""},
}

// DateInstanceProposalRels is where relationship names are stored.
var DateInstanceProposalRels = struct {
	DateInstanceRef string
	SuggestedByRef  string
}{
	DateInstanceRef: "DateInstanceRef",
	SuggestedByRef:  "SuggestedByRef",
}

// dateInstanceProposalR is where relationships are stored.
type dateInstanceProposalR struct {
	DateInstanceRef *DateInstance `boil:"DateInstanceRef" json:"DateInstanceRef" toml:"DateInstanceRef" yaml:"DateInstanceRef"`
	SuggestedByRef  *User         `boil:"SuggestedByRef" json:"SuggestedByRef" toml:"SuggestedByRef" yaml:"SuggestedByRef"`
}

// NewStruct creates a new relationship struct
func (*dateInstanceProposalR) NewStruct() *dateInstanceProposalR {
	return &dateInstanceProposalR{}
}

func (o *DateInstanceProposal) GetDateInstanceRef() *DateInstance {
	if o == nil {
		return nil
	}

	return o.R.GetDateInstanceRef()
}

func (r *dateInstanceProposalR) GetDateInstanceRef() *DateInstance {
	if r == nil {
		return nil
	}

	return r.DateInstanceRef
}

func (o *DateInstanceProposal) GetSuggestedByRef() *User {
	if o == nil {
		return nil
	}

	return o.R.GetSuggestedByRef()
}

func (r *dateInstanceProposalR) GetSuggestedByRef() *User {
	if r == nil {
		return nil
	}

	return r.SuggestedByRef
}

// dateInstanceProposalL is where Load methods for each relationship are stored.
type dateInstanceProposalL struct{}

var (
	dateInstanceProposalAllColumns            = []string{"id", "date_instance_ref_id", "suggested_by_ref_id", "proposed_time", "status", "created_at", "updated_at"}
	dateInstanceProposalColumnsWithoutDefault = []string{"date_instance_ref_id", "suggested_by_ref_id", "proposed_time"}
	dateInstanceProposalColumnsWithDefault    = []string{"id", "status", "created_at", "updated_at"}
	dateInstanceProposalPrimaryKeyColumns     = []string{"id"}
	dateInstanceProposalGeneratedColumns      = []string{}
)

type (
	// DateInstanceProposalSlice is an alias for a slice of pointers to DateInstanceProposal.
	// This should almost always be used instead of []DateInstanceProposal.
	DateInstanceProposalSlice []*DateInstanceProposal
	// DateInstanceProposalHook is the signature for custom DateInstanceProposal hook methods
	DateInstanceProposalHook func(context.Context, boil.ContextExecutor, *DateInstanceProposal) error

	dateInstanceProposalQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dateInstanceProposalType                 = reflect.TypeOf(&DateInstanceProposal{})
	dateInstanceProposalMapping              = queries.MakeStructMapping(dateInstanceProposalType)
	dateInstanceProposalPrimaryKeyMapping, _ = queries.BindMapping(dateInstanceProposalType, dateInstanceProposalMapping, dateInstanceProposalPrimaryKeyColumns)
	dateInstanceProposalInsertCacheMut       sync.RWMutex
	dateInstanceProposalInsertCache          = make(map[string]insertCache)
	dateInstanceProposalUpdateCacheMut       sync.RWMutex
	dateInstanceProposalUpdateCache          = make(map[string]updateCache)
	dateInstanceProposalUpsertCacheMut       sync.RWMutex
	dateInstanceProposalUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dateInstanceProposalAfterSelectMu sync.Mutex
var dateInstanceProposalAfterSelectHooks []DateInstanceProposalHook

var dateInstanceProposalBeforeInsertMu sync.Mutex
var dateInstanceProposalBeforeInsertHooks []DateInstanceProposalHook
var dateInstanceProposalAfterInsertMu sync.Mutex
var dateInstanceProposalAfterInsertHooks []DateInstanceProposalHook

var dateInstanceProposalBeforeUpdateMu sync.Mutex
var dateInstanceProposalBeforeUpdateHooks []DateInstanceProposalHook
var dateInstanceProposalAfterUpdateMu sync.Mutex
var dateInstanceProposalAfterUpdateHooks []DateInstanceProposalHook

var dateInstanceProposalBeforeDeleteMu sync.Mutex
var dateInstanceProposalBeforeDeleteHooks []DateInstanceProposalHook
var dateInstanceProposalAfterDeleteMu sync.Mutex
var dateInstanceProposalAfterDeleteHooks []DateInstanceProposalHook

var dateInstanceProposalBeforeUpsertMu sync.Mutex
var dateInstanceProposalBeforeUpsertHooks []DateInstanceProposalHook
var dateInstanceProposalAfterUpsertMu sync.Mutex
var dateInstanceProposalAfterUpsertHooks []DateInstanceProposalHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DateInstanceProposal) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DateInstanceProposal) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DateInstanceProposal) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DateInstanceProposal) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DateInstanceProposal) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DateInstanceProposal) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DateInstanceProposal) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DateInstanceProposal) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DateInstanceProposal) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dateInstanceProposalAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDateInstanceProposalHook registers your hook function for all future operations.
func AddDateInstanceProposalHook(hookPoint boil.HookPoint, dateInstanceProposalHook DateInstanceProposalHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dateInstanceProposalAfterSelectMu.Lock()
		dateInstanceProposalAfterSelectHooks = append(dateInstanceProposalAfterSelectHooks, dateInstanceProposalHook)
		dateInstanceProposalAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		dateInstanceProposalBeforeInsertMu.Lock()
		dateInstanceProposalBeforeInsertHooks = append(dateInstanceProposalBeforeInsertHooks, dateInstanceProposalHook)
		dateInstanceProposalBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		dateInstanceProposalAfterInsertMu.Lock()
		dateInstanceProposalAfterInsertHooks = append(dateInstanceProposalAfterInsertHooks, dateInstanceProposalHook)
		dateInstanceProposalAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		dateInstanceProposalBeforeUpdateMu.Lock()
		dateInstanceProposalBeforeUpdateHooks = append(dateInstanceProposalBeforeUpdateHooks, dateInstanceProposalHook)
		dateInstanceProposalBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		dateInstanceProposalAfterUpdateMu.Lock()
		dateInstanceProposalAfterUpdateHooks = append(dateInstanceProposalAfterUpdateHooks, dateInstanceProposalHook)
		dateInstanceProposalAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		dateInstanceProposalBeforeDeleteMu.Lock()
		dateInstanceProposalBeforeDeleteHooks = append(dateInstanceProposalBeforeDeleteHooks, dateInstanceProposalHook)
		dateInstanceProposalBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		dateInstanceProposalAfterDeleteMu.Lock()
		dateInstanceProposalAfterDeleteHooks = append(dateInstanceProposalAfterDeleteHooks, dateInstanceProposalHook)
		dateInstanceProposalAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		dateInstanceProposalBeforeUpsertMu.Lock()
		dateInstanceProposalBeforeUpsertHooks = append(dateInstanceProposalBeforeUpsertHooks, dateInstanceProposalHook)
		dateInstanceProposalBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		dateInstanceProposalAfterUpsertMu.Lock()
		dateInstanceProposalAfterUpsertHooks = append(dateInstanceProposalAfterUpsertHooks, dateInstanceProposalHook)
		dateInstanceProposalAfterUpsertMu.Unlock()
	}
}

// One returns a single dateInstanceProposal record from the query.
func (q dateInstanceProposalQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DateInstanceProposal, error) {
	o := &DateInstanceProposal{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for date_instance_proposal")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DateInstanceProposal records from the query.
func (q dateInstanceProposalQuery) All(ctx context.Context, exec boil.ContextExecutor) (DateInstanceProposalSlice, error) {
	var o []*DateInstanceProposal

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to DateInstanceProposal slice")
	}

	if len(dateInstanceProposalAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DateInstanceProposal records in the query.
func (q dateInstanceProposalQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count date_instance_proposal rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dateInstanceProposalQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if date_instance_proposal exists")
	}

	return count > 0, nil
}

// DateInstanceRef pointed to by the foreign key.
func (o *DateInstanceProposal) DateInstanceRef(mods ...qm.QueryMod) dateInstanceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DateInstanceRefID),
	}

	queryMods = append(queryMods, mods...)

	return DateInstances(queryMods...)
}

// SuggestedByRef pointed to by the foreign key.
func (o *DateInstanceProposal) SuggestedByRef(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SuggestedByRefID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadDateInstanceRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dateInstanceProposalL) LoadDateInstanceRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDateInstanceProposal interface{}, mods queries.Applicator) error {
	var slice []*DateInstanceProposal
	var object *DateInstanceProposal

	if singular {
		var ok bool
		object, ok = maybeDateInstanceProposal.(*DateInstanceProposal)
		if !ok {
			object = new(DateInstanceProposal)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDateInstanceProposal)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDateInstanceProposal))
			}
		}
	} else {
		s, ok := maybeDateInstanceProposal.(*[]*DateInstanceProposal)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDateInstanceProposal)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDateInstanceProposal))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dateInstanceProposalR{}
		}
		args[object.DateInstanceRefID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dateInstanceProposalR{}
			}

			args[obj.DateInstanceRefID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`date_instance`),
		qm.WhereIn(`date_instance.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DateInstance")
	}

	var resultSlice []*DateInstance
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DateInstance")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for date_instance")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for date_instance")
	}

	if len(dateInstanceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DateInstanceRef = foreign
		if foreign.R == nil {
			foreign.R = &dateInstanceR{}
		}
		foreign.R.DateInstanceRefDateInstanceProposals = append(foreign.R.DateInstanceRefDateInstanceProposals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DateInstanceRefID == foreign.ID {
				local.R.DateInstanceRef = foreign
				if foreign.R == nil {
					foreign.R = &dateInstanceR{}
				}
				foreign.R.DateInstanceRefDateInstanceProposals = append(foreign.R.DateInstanceRefDateInstanceProposals, local)
				break
			}
		}
	}

	return nil
}

// LoadSuggestedByRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dateInstanceProposalL) LoadSuggestedByRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDateInstanceProposal interface{}, mods queries.Applicator) error {
	var slice []*DateInstanceProposal
	var object *DateInstanceProposal

	if singular {
		var ok bool
		object, ok = maybeDateInstanceProposal.(*DateInstanceProposal)
		if !ok {
			object = new(DateInstanceProposal)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDateInstanceProposal)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDateInstanceProposal))
			}
		}
	} else {
		s, ok := maybeDateInstanceProposal.(*[]*DateInstanceProposal)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDateInstanceProposal)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDateInstanceProposal))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dateInstanceProposalR{}
		}
		args[object.SuggestedByRefID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dateInstanceProposalR{}
			}

			args[obj.SuggestedByRefID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SuggestedByRef = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SuggestedByRefDateInstanceProposals = append(foreign.R.SuggestedByRefDateInstanceProposals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SuggestedByRefID == foreign.ID {
				local.R.SuggestedByRef = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SuggestedByRefDateInstanceProposals = append(foreign.R.SuggestedByRefDateInstanceProposals, local)
				break
			}
		}
	}

	return nil
}

// SetDateInstanceRef of the dateInstanceProposal to the related item.
// Sets o.R.DateInstanceRef to related.
// Adds o to related.R.DateInstanceRefDateInstanceProposals.
func (o *DateInstanceProposal) SetDateInstanceRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DateInstance) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"date_instance_proposal\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"date_instance_ref_id"}),
		strmangle.WhereClause("\"", "\"", 2, dateInstanceProposalPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DateInstanceRefID = related.ID
	if o.R == nil {
		o.R = &dateInstanceProposalR{
			DateInstanceRef: related,
		}
	} else {
		o.R.DateInstanceRef = related
	}

	if related.R == nil {
		related.R = &dateInstanceR{
			DateInstanceRefDateInstanceProposals: DateInstanceProposalSlice{o},
		}
	} else {
		related.R.DateInstanceRefDateInstanceProposals = append(related.R.DateInstanceRefDateInstanceProposals, o)
	}

	return nil
}

// SetSuggestedByRef of the dateInstanceProposal to the related item.
// Sets o.R.SuggestedByRef to related.
// Adds o to related.R.SuggestedByRefDateInstanceProposals.
func (o *DateInstanceProposal) SetSuggestedByRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"date_instance_proposal\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"suggested_by_ref_id"}),
		strmangle.WhereClause("\"", "\"", 2, dateInstanceProposalPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SuggestedByRefID = related.ID
	if o.R == nil {
		o.R = &dateInstanceProposalR{
			SuggestedByRef: related,
		}
	} else {
		o.R.SuggestedByRef = related
	}

	if related.R == nil {
		related.R = &userR{
			SuggestedByRefDateInstanceProposals: DateInstanceProposalSlice{o},
		}
	} else {
		related.R.SuggestedByRefDateInstanceProposals = append(related.R.SuggestedByRefDateInstanceProposals, o)
	}

	return nil
}

// DateInstanceProposals retrieves all the records using an executor.
func DateInstanceProposals(mods ...qm.QueryMod) dateInstanceProposalQuery {
	mods = append(mods, qm.From("\"date_instance_proposal\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"date_instance_proposal\".*"})
	}

	return dateInstanceProposalQuery{q}
}

// FindDateInstanceProposal retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDateInstanceProposal(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*DateInstanceProposal, error) {
	dateInstanceProposalObj := &DateInstanceProposal{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"date_instance_proposal\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dateInstanceProposalObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from date_instance_proposal")
	}

	if err = dateInstanceProposalObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dateInstanceProposalObj, err
	}

	return dateInstanceProposalObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DateInstanceProposal) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no date_instance_proposal provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dateInstanceProposalColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dateInstanceProposalInsertCacheMut.RLock()
	cache, cached := dateInstanceProposalInsertCache[key]
	dateInstanceProposalInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dateInstanceProposalAllColumns,
			dateInstanceProposalColumnsWithDefault,
			dateInstanceProposalColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dateInstanceProposalType, dateInstanceProposalMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dateInstanceProposalType, dateInstanceProposalMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"date_instance_proposal\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"date_instance_proposal\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into date_instance_proposal")
	}

	if !cached {
		dateInstanceProposalInsertCacheMut.Lock()
		dateInstanceProposalInsertCache[key] = cache
		dateInstanceProposalInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DateInstanceProposal.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DateInstanceProposal) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dateInstanceProposalUpdateCacheMut.RLock()
	cache, cached := dateInstanceProposalUpdateCache[key]
	dateInstanceProposalUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dateInstanceProposalAllColumns,
			dateInstanceProposalPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update date_instance_proposal, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"date_instance_proposal\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, dateInstanceProposalPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dateInstanceProposalType, dateInstanceProposalMapping, append(wl, dateInstanceProposalPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update date_instance_proposal row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for date_instance_proposal")
	}

	if !cached {
		dateInstanceProposalUpdateCacheMut.Lock()
		dateInstanceProposalUpdateCache[key] = cache
		dateInstanceProposalUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dateInstanceProposalQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for date_instance_proposal")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for date_instance_proposal")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DateInstanceProposalSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dateInstanceProposalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"date_instance_proposal\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, dateInstanceProposalPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in dateInstanceProposal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all dateInstanceProposal")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DateInstanceProposal) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no date_instance_proposal provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dateInstanceProposalColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dateInstanceProposalUpsertCacheMut.RLock()
	cache, cached := dateInstanceProposalUpsertCache[key]
	dateInstanceProposalUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			dateInstanceProposalAllColumns,
			dateInstanceProposalColumnsWithDefault,
			dateInstanceProposalColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dateInstanceProposalAllColumns,
			dateInstanceProposalPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert date_instance_proposal, could not build update column list")
		}

		ret := strmangle.SetComplement(dateInstanceProposalAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(dateInstanceProposalPrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert date_instance_proposal, could not build conflict column list")
			}

			conflict = make([]string, len(dateInstanceProposalPrimaryKeyColumns))
			copy(conflict, dateInstanceProposalPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"date_instance_proposal\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(dateInstanceProposalType, dateInstanceProposalMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dateInstanceProposalType, dateInstanceProposalMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert date_instance_proposal")
	}

	if !cached {
		dateInstanceProposalUpsertCacheMut.Lock()
		dateInstanceProposalUpsertCache[key] = cache
		dateInstanceProposalUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DateInstanceProposal record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DateInstanceProposal) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no DateInstanceProposal provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dateInstanceProposalPrimaryKeyMapping)
	sql := "DELETE FROM \"date_instance_proposal\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from date_instance_proposal")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for date_instance_proposal")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dateInstanceProposalQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no dateInstanceProposalQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from date_instance_proposal")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for date_instance_proposal")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DateInstanceProposalSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dateInstanceProposalBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dateInstanceProposalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"date_instance_proposal\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, dateInstanceProposalPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from dateInstanceProposal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for date_instance_proposal")
	}

	if len(dateInstanceProposalAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DateInstanceProposal) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDateInstanceProposal(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DateInstanceProposalSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DateInstanceProposalSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dateInstanceProposalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"date_instance_proposal\".* FROM \"date_instance_proposal\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, dateInstanceProposalPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in DateInstanceProposalSlice")
	}

	*o = slice

	return nil
}

// DateInstanceProposalExists checks if the DateInstanceProposal row exists.
func DateInstanceProposalExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"date_instance_proposal\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if date_instance_proposal exists")
	}

	return exists, nil
}

// Exists checks if the DateInstanceProposal row exists.
func (o *DateInstanceProposal) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DateInstanceProposalExists(ctx, exec, o.ID)
}
