// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserDatingPreference is an object representing the database table.
type UserDatingPreference struct {
	ID               string `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID           string `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	DatingPreference string `boil:"dating_preference" json:"dating_preference" toml:"dating_preference" yaml:"dating_preference"`

	R *userDatingPreferenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userDatingPreferenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserDatingPreferenceColumns = struct {
	ID               string
	UserID           string
	DatingPreference string
}{
	ID:               "id",
	UserID:           "user_id",
	DatingPreference: "dating_preference",
}

var UserDatingPreferenceTableColumns = struct {
	ID               string
	UserID           string
	DatingPreference string
}{
	ID:               "user_dating_preferences.id",
	UserID:           "user_dating_preferences.user_id",
	DatingPreference: "user_dating_preferences.dating_preference",
}

// Generated where

var UserDatingPreferenceWhere = struct {
	ID               whereHelperstring
	UserID           whereHelperstring
	DatingPreference whereHelperstring
}{
	ID:               whereHelperstring{field: "\"user_dating_preferences\".\"id\""},
	UserID:           whereHelperstring{field: "\"user_dating_preferences\".\"user_id\""},
	DatingPreference: whereHelperstring{field: "\"user_dating_preferences\".\"dating_preference\""},
}

// UserDatingPreferenceRels is where relationship names are stored.
var UserDatingPreferenceRels = struct {
	User string
}{
	User: "User",
}

// userDatingPreferenceR is where relationships are stored.
type userDatingPreferenceR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userDatingPreferenceR) NewStruct() *userDatingPreferenceR {
	return &userDatingPreferenceR{}
}

func (o *UserDatingPreference) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *userDatingPreferenceR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// userDatingPreferenceL is where Load methods for each relationship are stored.
type userDatingPreferenceL struct{}

var (
	userDatingPreferenceAllColumns            = []string{"id", "user_id", "dating_preference"}
	userDatingPreferenceColumnsWithoutDefault = []string{"user_id", "dating_preference"}
	userDatingPreferenceColumnsWithDefault    = []string{"id"}
	userDatingPreferencePrimaryKeyColumns     = []string{"id"}
	userDatingPreferenceGeneratedColumns      = []string{}
)

type (
	// UserDatingPreferenceSlice is an alias for a slice of pointers to UserDatingPreference.
	// This should almost always be used instead of []UserDatingPreference.
	UserDatingPreferenceSlice []*UserDatingPreference
	// UserDatingPreferenceHook is the signature for custom UserDatingPreference hook methods
	UserDatingPreferenceHook func(context.Context, boil.ContextExecutor, *UserDatingPreference) error

	userDatingPreferenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userDatingPreferenceType                 = reflect.TypeOf(&UserDatingPreference{})
	userDatingPreferenceMapping              = queries.MakeStructMapping(userDatingPreferenceType)
	userDatingPreferencePrimaryKeyMapping, _ = queries.BindMapping(userDatingPreferenceType, userDatingPreferenceMapping, userDatingPreferencePrimaryKeyColumns)
	userDatingPreferenceInsertCacheMut       sync.RWMutex
	userDatingPreferenceInsertCache          = make(map[string]insertCache)
	userDatingPreferenceUpdateCacheMut       sync.RWMutex
	userDatingPreferenceUpdateCache          = make(map[string]updateCache)
	userDatingPreferenceUpsertCacheMut       sync.RWMutex
	userDatingPreferenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userDatingPreferenceAfterSelectMu sync.Mutex
var userDatingPreferenceAfterSelectHooks []UserDatingPreferenceHook

var userDatingPreferenceBeforeInsertMu sync.Mutex
var userDatingPreferenceBeforeInsertHooks []UserDatingPreferenceHook
var userDatingPreferenceAfterInsertMu sync.Mutex
var userDatingPreferenceAfterInsertHooks []UserDatingPreferenceHook

var userDatingPreferenceBeforeUpdateMu sync.Mutex
var userDatingPreferenceBeforeUpdateHooks []UserDatingPreferenceHook
var userDatingPreferenceAfterUpdateMu sync.Mutex
var userDatingPreferenceAfterUpdateHooks []UserDatingPreferenceHook

var userDatingPreferenceBeforeDeleteMu sync.Mutex
var userDatingPreferenceBeforeDeleteHooks []UserDatingPreferenceHook
var userDatingPreferenceAfterDeleteMu sync.Mutex
var userDatingPreferenceAfterDeleteHooks []UserDatingPreferenceHook

var userDatingPreferenceBeforeUpsertMu sync.Mutex
var userDatingPreferenceBeforeUpsertHooks []UserDatingPreferenceHook
var userDatingPreferenceAfterUpsertMu sync.Mutex
var userDatingPreferenceAfterUpsertHooks []UserDatingPreferenceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserDatingPreference) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserDatingPreference) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserDatingPreference) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserDatingPreference) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserDatingPreference) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserDatingPreference) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserDatingPreference) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserDatingPreference) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserDatingPreference) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDatingPreferenceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserDatingPreferenceHook registers your hook function for all future operations.
func AddUserDatingPreferenceHook(hookPoint boil.HookPoint, userDatingPreferenceHook UserDatingPreferenceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userDatingPreferenceAfterSelectMu.Lock()
		userDatingPreferenceAfterSelectHooks = append(userDatingPreferenceAfterSelectHooks, userDatingPreferenceHook)
		userDatingPreferenceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userDatingPreferenceBeforeInsertMu.Lock()
		userDatingPreferenceBeforeInsertHooks = append(userDatingPreferenceBeforeInsertHooks, userDatingPreferenceHook)
		userDatingPreferenceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userDatingPreferenceAfterInsertMu.Lock()
		userDatingPreferenceAfterInsertHooks = append(userDatingPreferenceAfterInsertHooks, userDatingPreferenceHook)
		userDatingPreferenceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userDatingPreferenceBeforeUpdateMu.Lock()
		userDatingPreferenceBeforeUpdateHooks = append(userDatingPreferenceBeforeUpdateHooks, userDatingPreferenceHook)
		userDatingPreferenceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userDatingPreferenceAfterUpdateMu.Lock()
		userDatingPreferenceAfterUpdateHooks = append(userDatingPreferenceAfterUpdateHooks, userDatingPreferenceHook)
		userDatingPreferenceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userDatingPreferenceBeforeDeleteMu.Lock()
		userDatingPreferenceBeforeDeleteHooks = append(userDatingPreferenceBeforeDeleteHooks, userDatingPreferenceHook)
		userDatingPreferenceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userDatingPreferenceAfterDeleteMu.Lock()
		userDatingPreferenceAfterDeleteHooks = append(userDatingPreferenceAfterDeleteHooks, userDatingPreferenceHook)
		userDatingPreferenceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userDatingPreferenceBeforeUpsertMu.Lock()
		userDatingPreferenceBeforeUpsertHooks = append(userDatingPreferenceBeforeUpsertHooks, userDatingPreferenceHook)
		userDatingPreferenceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userDatingPreferenceAfterUpsertMu.Lock()
		userDatingPreferenceAfterUpsertHooks = append(userDatingPreferenceAfterUpsertHooks, userDatingPreferenceHook)
		userDatingPreferenceAfterUpsertMu.Unlock()
	}
}

// One returns a single userDatingPreference record from the query.
func (q userDatingPreferenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserDatingPreference, error) {
	o := &UserDatingPreference{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for user_dating_preferences")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserDatingPreference records from the query.
func (q userDatingPreferenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserDatingPreferenceSlice, error) {
	var o []*UserDatingPreference

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to UserDatingPreference slice")
	}

	if len(userDatingPreferenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserDatingPreference records in the query.
func (q userDatingPreferenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count user_dating_preferences rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userDatingPreferenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if user_dating_preferences exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserDatingPreference) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userDatingPreferenceL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserDatingPreference interface{}, mods queries.Applicator) error {
	var slice []*UserDatingPreference
	var object *UserDatingPreference

	if singular {
		var ok bool
		object, ok = maybeUserDatingPreference.(*UserDatingPreference)
		if !ok {
			object = new(UserDatingPreference)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserDatingPreference)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserDatingPreference))
			}
		}
	} else {
		s, ok := maybeUserDatingPreference.(*[]*UserDatingPreference)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserDatingPreference)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserDatingPreference))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userDatingPreferenceR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userDatingPreferenceR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserDatingPreferences = append(foreign.R.UserDatingPreferences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserDatingPreferences = append(foreign.R.UserDatingPreferences, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the userDatingPreference to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserDatingPreferences.
func (o *UserDatingPreference) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_dating_preferences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userDatingPreferencePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userDatingPreferenceR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserDatingPreferences: UserDatingPreferenceSlice{o},
		}
	} else {
		related.R.UserDatingPreferences = append(related.R.UserDatingPreferences, o)
	}

	return nil
}

// UserDatingPreferences retrieves all the records using an executor.
func UserDatingPreferences(mods ...qm.QueryMod) userDatingPreferenceQuery {
	mods = append(mods, qm.From("\"user_dating_preferences\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_dating_preferences\".*"})
	}

	return userDatingPreferenceQuery{q}
}

// FindUserDatingPreference retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserDatingPreference(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserDatingPreference, error) {
	userDatingPreferenceObj := &UserDatingPreference{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_dating_preferences\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userDatingPreferenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from user_dating_preferences")
	}

	if err = userDatingPreferenceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userDatingPreferenceObj, err
	}

	return userDatingPreferenceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserDatingPreference) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no user_dating_preferences provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userDatingPreferenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userDatingPreferenceInsertCacheMut.RLock()
	cache, cached := userDatingPreferenceInsertCache[key]
	userDatingPreferenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userDatingPreferenceAllColumns,
			userDatingPreferenceColumnsWithDefault,
			userDatingPreferenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userDatingPreferenceType, userDatingPreferenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userDatingPreferenceType, userDatingPreferenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_dating_preferences\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_dating_preferences\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into user_dating_preferences")
	}

	if !cached {
		userDatingPreferenceInsertCacheMut.Lock()
		userDatingPreferenceInsertCache[key] = cache
		userDatingPreferenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserDatingPreference.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserDatingPreference) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userDatingPreferenceUpdateCacheMut.RLock()
	cache, cached := userDatingPreferenceUpdateCache[key]
	userDatingPreferenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userDatingPreferenceAllColumns,
			userDatingPreferencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update user_dating_preferences, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_dating_preferences\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userDatingPreferencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userDatingPreferenceType, userDatingPreferenceMapping, append(wl, userDatingPreferencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update user_dating_preferences row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for user_dating_preferences")
	}

	if !cached {
		userDatingPreferenceUpdateCacheMut.Lock()
		userDatingPreferenceUpdateCache[key] = cache
		userDatingPreferenceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userDatingPreferenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for user_dating_preferences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for user_dating_preferences")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserDatingPreferenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userDatingPreferencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_dating_preferences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userDatingPreferencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in userDatingPreference slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all userDatingPreference")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserDatingPreference) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no user_dating_preferences provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userDatingPreferenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userDatingPreferenceUpsertCacheMut.RLock()
	cache, cached := userDatingPreferenceUpsertCache[key]
	userDatingPreferenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userDatingPreferenceAllColumns,
			userDatingPreferenceColumnsWithDefault,
			userDatingPreferenceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userDatingPreferenceAllColumns,
			userDatingPreferencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert user_dating_preferences, could not build update column list")
		}

		ret := strmangle.SetComplement(userDatingPreferenceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userDatingPreferencePrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert user_dating_preferences, could not build conflict column list")
			}

			conflict = make([]string, len(userDatingPreferencePrimaryKeyColumns))
			copy(conflict, userDatingPreferencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_dating_preferences\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userDatingPreferenceType, userDatingPreferenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userDatingPreferenceType, userDatingPreferenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert user_dating_preferences")
	}

	if !cached {
		userDatingPreferenceUpsertCacheMut.Lock()
		userDatingPreferenceUpsertCache[key] = cache
		userDatingPreferenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserDatingPreference record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserDatingPreference) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no UserDatingPreference provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userDatingPreferencePrimaryKeyMapping)
	sql := "DELETE FROM \"user_dating_preferences\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from user_dating_preferences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for user_dating_preferences")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userDatingPreferenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no userDatingPreferenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from user_dating_preferences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for user_dating_preferences")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserDatingPreferenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userDatingPreferenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userDatingPreferencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_dating_preferences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userDatingPreferencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from userDatingPreference slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for user_dating_preferences")
	}

	if len(userDatingPreferenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserDatingPreference) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserDatingPreference(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserDatingPreferenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserDatingPreferenceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userDatingPreferencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_dating_preferences\".* FROM \"user_dating_preferences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userDatingPreferencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in UserDatingPreferenceSlice")
	}

	*o = slice

	return nil
}

// UserDatingPreferenceExists checks if the UserDatingPreference row exists.
func UserDatingPreferenceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_dating_preferences\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if user_dating_preferences exists")
	}

	return exists, nil
}

// Exists checks if the UserDatingPreference row exists.
func (o *UserDatingPreference) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserDatingPreferenceExists(ctx, exec, o.ID)
}
