// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserAiContext is an object representing the database table.
type UserAiContext struct {
	ID            string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID        string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	AiContextType string    `boil:"ai_context_type" json:"ai_context_type" toml:"ai_context_type" yaml:"ai_context_type"`
	Context       string    `boil:"context" json:"context" toml:"context" yaml:"context"`
	CreatedAt     null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt     null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	IsActive      null.Bool `boil:"is_active" json:"is_active,omitempty" toml:"is_active" yaml:"is_active,omitempty"`

	R *userAiContextR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userAiContextL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserAiContextColumns = struct {
	ID            string
	UserID        string
	AiContextType string
	Context       string
	CreatedAt     string
	UpdatedAt     string
	IsActive      string
}{
	ID:            "id",
	UserID:        "user_id",
	AiContextType: "ai_context_type",
	Context:       "context",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	IsActive:      "is_active",
}

var UserAiContextTableColumns = struct {
	ID            string
	UserID        string
	AiContextType string
	Context       string
	CreatedAt     string
	UpdatedAt     string
	IsActive      string
}{
	ID:            "user_ai_context.id",
	UserID:        "user_ai_context.user_id",
	AiContextType: "user_ai_context.ai_context_type",
	Context:       "user_ai_context.context",
	CreatedAt:     "user_ai_context.created_at",
	UpdatedAt:     "user_ai_context.updated_at",
	IsActive:      "user_ai_context.is_active",
}

// Generated where

var UserAiContextWhere = struct {
	ID            whereHelperstring
	UserID        whereHelperstring
	AiContextType whereHelperstring
	Context       whereHelperstring
	CreatedAt     whereHelpernull_Time
	UpdatedAt     whereHelpernull_Time
	IsActive      whereHelpernull_Bool
}{
	ID:            whereHelperstring{field: "\"user_ai_context\".\"id\""},
	UserID:        whereHelperstring{field: "\"user_ai_context\".\"user_id\""},
	AiContextType: whereHelperstring{field: "\"user_ai_context\".\"ai_context_type\""},
	Context:       whereHelperstring{field: "\"user_ai_context\".\"context\""},
	CreatedAt:     whereHelpernull_Time{field: "\"user_ai_context\".\"created_at\""},
	UpdatedAt:     whereHelpernull_Time{field: "\"user_ai_context\".\"updated_at\""},
	IsActive:      whereHelpernull_Bool{field: "\"user_ai_context\".\"is_active\""},
}

// UserAiContextRels is where relationship names are stored.
var UserAiContextRels = struct {
	User string
}{
	User: "User",
}

// userAiContextR is where relationships are stored.
type userAiContextR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userAiContextR) NewStruct() *userAiContextR {
	return &userAiContextR{}
}

func (o *UserAiContext) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *userAiContextR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// userAiContextL is where Load methods for each relationship are stored.
type userAiContextL struct{}

var (
	userAiContextAllColumns            = []string{"id", "user_id", "ai_context_type", "context", "created_at", "updated_at", "is_active"}
	userAiContextColumnsWithoutDefault = []string{"user_id", "context"}
	userAiContextColumnsWithDefault    = []string{"id", "ai_context_type", "created_at", "updated_at", "is_active"}
	userAiContextPrimaryKeyColumns     = []string{"id"}
	userAiContextGeneratedColumns      = []string{}
)

type (
	// UserAiContextSlice is an alias for a slice of pointers to UserAiContext.
	// This should almost always be used instead of []UserAiContext.
	UserAiContextSlice []*UserAiContext
	// UserAiContextHook is the signature for custom UserAiContext hook methods
	UserAiContextHook func(context.Context, boil.ContextExecutor, *UserAiContext) error

	userAiContextQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userAiContextType                 = reflect.TypeOf(&UserAiContext{})
	userAiContextMapping              = queries.MakeStructMapping(userAiContextType)
	userAiContextPrimaryKeyMapping, _ = queries.BindMapping(userAiContextType, userAiContextMapping, userAiContextPrimaryKeyColumns)
	userAiContextInsertCacheMut       sync.RWMutex
	userAiContextInsertCache          = make(map[string]insertCache)
	userAiContextUpdateCacheMut       sync.RWMutex
	userAiContextUpdateCache          = make(map[string]updateCache)
	userAiContextUpsertCacheMut       sync.RWMutex
	userAiContextUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userAiContextAfterSelectMu sync.Mutex
var userAiContextAfterSelectHooks []UserAiContextHook

var userAiContextBeforeInsertMu sync.Mutex
var userAiContextBeforeInsertHooks []UserAiContextHook
var userAiContextAfterInsertMu sync.Mutex
var userAiContextAfterInsertHooks []UserAiContextHook

var userAiContextBeforeUpdateMu sync.Mutex
var userAiContextBeforeUpdateHooks []UserAiContextHook
var userAiContextAfterUpdateMu sync.Mutex
var userAiContextAfterUpdateHooks []UserAiContextHook

var userAiContextBeforeDeleteMu sync.Mutex
var userAiContextBeforeDeleteHooks []UserAiContextHook
var userAiContextAfterDeleteMu sync.Mutex
var userAiContextAfterDeleteHooks []UserAiContextHook

var userAiContextBeforeUpsertMu sync.Mutex
var userAiContextBeforeUpsertHooks []UserAiContextHook
var userAiContextAfterUpsertMu sync.Mutex
var userAiContextAfterUpsertHooks []UserAiContextHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserAiContext) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserAiContext) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserAiContext) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserAiContext) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserAiContext) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserAiContext) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserAiContext) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserAiContext) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserAiContext) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userAiContextAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserAiContextHook registers your hook function for all future operations.
func AddUserAiContextHook(hookPoint boil.HookPoint, userAiContextHook UserAiContextHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userAiContextAfterSelectMu.Lock()
		userAiContextAfterSelectHooks = append(userAiContextAfterSelectHooks, userAiContextHook)
		userAiContextAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userAiContextBeforeInsertMu.Lock()
		userAiContextBeforeInsertHooks = append(userAiContextBeforeInsertHooks, userAiContextHook)
		userAiContextBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userAiContextAfterInsertMu.Lock()
		userAiContextAfterInsertHooks = append(userAiContextAfterInsertHooks, userAiContextHook)
		userAiContextAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userAiContextBeforeUpdateMu.Lock()
		userAiContextBeforeUpdateHooks = append(userAiContextBeforeUpdateHooks, userAiContextHook)
		userAiContextBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userAiContextAfterUpdateMu.Lock()
		userAiContextAfterUpdateHooks = append(userAiContextAfterUpdateHooks, userAiContextHook)
		userAiContextAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userAiContextBeforeDeleteMu.Lock()
		userAiContextBeforeDeleteHooks = append(userAiContextBeforeDeleteHooks, userAiContextHook)
		userAiContextBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userAiContextAfterDeleteMu.Lock()
		userAiContextAfterDeleteHooks = append(userAiContextAfterDeleteHooks, userAiContextHook)
		userAiContextAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userAiContextBeforeUpsertMu.Lock()
		userAiContextBeforeUpsertHooks = append(userAiContextBeforeUpsertHooks, userAiContextHook)
		userAiContextBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userAiContextAfterUpsertMu.Lock()
		userAiContextAfterUpsertHooks = append(userAiContextAfterUpsertHooks, userAiContextHook)
		userAiContextAfterUpsertMu.Unlock()
	}
}

// One returns a single userAiContext record from the query.
func (q userAiContextQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserAiContext, error) {
	o := &UserAiContext{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for user_ai_context")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserAiContext records from the query.
func (q userAiContextQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserAiContextSlice, error) {
	var o []*UserAiContext

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to UserAiContext slice")
	}

	if len(userAiContextAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserAiContext records in the query.
func (q userAiContextQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count user_ai_context rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userAiContextQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if user_ai_context exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserAiContext) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userAiContextL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserAiContext interface{}, mods queries.Applicator) error {
	var slice []*UserAiContext
	var object *UserAiContext

	if singular {
		var ok bool
		object, ok = maybeUserAiContext.(*UserAiContext)
		if !ok {
			object = new(UserAiContext)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserAiContext)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserAiContext))
			}
		}
	} else {
		s, ok := maybeUserAiContext.(*[]*UserAiContext)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserAiContext)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserAiContext))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userAiContextR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userAiContextR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserAiContexts = append(foreign.R.UserAiContexts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserAiContexts = append(foreign.R.UserAiContexts, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the userAiContext to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAiContexts.
func (o *UserAiContext) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_ai_context\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userAiContextPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userAiContextR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserAiContexts: UserAiContextSlice{o},
		}
	} else {
		related.R.UserAiContexts = append(related.R.UserAiContexts, o)
	}

	return nil
}

// UserAiContexts retrieves all the records using an executor.
func UserAiContexts(mods ...qm.QueryMod) userAiContextQuery {
	mods = append(mods, qm.From("\"user_ai_context\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_ai_context\".*"})
	}

	return userAiContextQuery{q}
}

// FindUserAiContext retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserAiContext(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserAiContext, error) {
	userAiContextObj := &UserAiContext{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_ai_context\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userAiContextObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from user_ai_context")
	}

	if err = userAiContextObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userAiContextObj, err
	}

	return userAiContextObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserAiContext) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no user_ai_context provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userAiContextColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userAiContextInsertCacheMut.RLock()
	cache, cached := userAiContextInsertCache[key]
	userAiContextInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userAiContextAllColumns,
			userAiContextColumnsWithDefault,
			userAiContextColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userAiContextType, userAiContextMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userAiContextType, userAiContextMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_ai_context\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_ai_context\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into user_ai_context")
	}

	if !cached {
		userAiContextInsertCacheMut.Lock()
		userAiContextInsertCache[key] = cache
		userAiContextInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserAiContext.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserAiContext) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userAiContextUpdateCacheMut.RLock()
	cache, cached := userAiContextUpdateCache[key]
	userAiContextUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userAiContextAllColumns,
			userAiContextPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update user_ai_context, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_ai_context\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userAiContextPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userAiContextType, userAiContextMapping, append(wl, userAiContextPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update user_ai_context row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for user_ai_context")
	}

	if !cached {
		userAiContextUpdateCacheMut.Lock()
		userAiContextUpdateCache[key] = cache
		userAiContextUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userAiContextQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for user_ai_context")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for user_ai_context")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserAiContextSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAiContextPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_ai_context\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userAiContextPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in userAiContext slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all userAiContext")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserAiContext) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no user_ai_context provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userAiContextColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userAiContextUpsertCacheMut.RLock()
	cache, cached := userAiContextUpsertCache[key]
	userAiContextUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userAiContextAllColumns,
			userAiContextColumnsWithDefault,
			userAiContextColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userAiContextAllColumns,
			userAiContextPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert user_ai_context, could not build update column list")
		}

		ret := strmangle.SetComplement(userAiContextAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userAiContextPrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert user_ai_context, could not build conflict column list")
			}

			conflict = make([]string, len(userAiContextPrimaryKeyColumns))
			copy(conflict, userAiContextPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_ai_context\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userAiContextType, userAiContextMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userAiContextType, userAiContextMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert user_ai_context")
	}

	if !cached {
		userAiContextUpsertCacheMut.Lock()
		userAiContextUpsertCache[key] = cache
		userAiContextUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserAiContext record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserAiContext) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no UserAiContext provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userAiContextPrimaryKeyMapping)
	sql := "DELETE FROM \"user_ai_context\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from user_ai_context")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for user_ai_context")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userAiContextQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no userAiContextQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from user_ai_context")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for user_ai_context")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserAiContextSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userAiContextBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAiContextPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_ai_context\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userAiContextPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from userAiContext slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for user_ai_context")
	}

	if len(userAiContextAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserAiContext) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserAiContext(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserAiContextSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserAiContextSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAiContextPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_ai_context\".* FROM \"user_ai_context\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userAiContextPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in UserAiContextSlice")
	}

	*o = slice

	return nil
}

// UserAiContextExists checks if the UserAiContext row exists.
func UserAiContextExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_ai_context\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if user_ai_context exists")
	}

	return exists, nil
}

// Exists checks if the UserAiContext row exists.
func (o *UserAiContext) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserAiContextExists(ctx, exec, o.ID)
}
