// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserMobilityConstraint is an object representing the database table.
type UserMobilityConstraint struct {
	ID                 string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID             string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	MobilityConstraint string    `boil:"mobility_constraint" json:"mobility_constraint" toml:"mobility_constraint" yaml:"mobility_constraint"`
	CreatedAt          null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`

	R *userMobilityConstraintR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userMobilityConstraintL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserMobilityConstraintColumns = struct {
	ID                 string
	UserID             string
	MobilityConstraint string
	CreatedAt          string
}{
	ID:                 "id",
	UserID:             "user_id",
	MobilityConstraint: "mobility_constraint",
	CreatedAt:          "created_at",
}

var UserMobilityConstraintTableColumns = struct {
	ID                 string
	UserID             string
	MobilityConstraint string
	CreatedAt          string
}{
	ID:                 "user_mobility_constraint.id",
	UserID:             "user_mobility_constraint.user_id",
	MobilityConstraint: "user_mobility_constraint.mobility_constraint",
	CreatedAt:          "user_mobility_constraint.created_at",
}

// Generated where

var UserMobilityConstraintWhere = struct {
	ID                 whereHelperstring
	UserID             whereHelperstring
	MobilityConstraint whereHelperstring
	CreatedAt          whereHelpernull_Time
}{
	ID:                 whereHelperstring{field: "\"user_mobility_constraint\".\"id\""},
	UserID:             whereHelperstring{field: "\"user_mobility_constraint\".\"user_id\""},
	MobilityConstraint: whereHelperstring{field: "\"user_mobility_constraint\".\"mobility_constraint\""},
	CreatedAt:          whereHelpernull_Time{field: "\"user_mobility_constraint\".\"created_at\""},
}

// UserMobilityConstraintRels is where relationship names are stored.
var UserMobilityConstraintRels = struct {
	User string
}{
	User: "User",
}

// userMobilityConstraintR is where relationships are stored.
type userMobilityConstraintR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userMobilityConstraintR) NewStruct() *userMobilityConstraintR {
	return &userMobilityConstraintR{}
}

func (o *UserMobilityConstraint) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *userMobilityConstraintR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// userMobilityConstraintL is where Load methods for each relationship are stored.
type userMobilityConstraintL struct{}

var (
	userMobilityConstraintAllColumns            = []string{"id", "user_id", "mobility_constraint", "created_at"}
	userMobilityConstraintColumnsWithoutDefault = []string{"user_id", "mobility_constraint"}
	userMobilityConstraintColumnsWithDefault    = []string{"id", "created_at"}
	userMobilityConstraintPrimaryKeyColumns     = []string{"id"}
	userMobilityConstraintGeneratedColumns      = []string{}
)

type (
	// UserMobilityConstraintSlice is an alias for a slice of pointers to UserMobilityConstraint.
	// This should almost always be used instead of []UserMobilityConstraint.
	UserMobilityConstraintSlice []*UserMobilityConstraint
	// UserMobilityConstraintHook is the signature for custom UserMobilityConstraint hook methods
	UserMobilityConstraintHook func(context.Context, boil.ContextExecutor, *UserMobilityConstraint) error

	userMobilityConstraintQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userMobilityConstraintType                 = reflect.TypeOf(&UserMobilityConstraint{})
	userMobilityConstraintMapping              = queries.MakeStructMapping(userMobilityConstraintType)
	userMobilityConstraintPrimaryKeyMapping, _ = queries.BindMapping(userMobilityConstraintType, userMobilityConstraintMapping, userMobilityConstraintPrimaryKeyColumns)
	userMobilityConstraintInsertCacheMut       sync.RWMutex
	userMobilityConstraintInsertCache          = make(map[string]insertCache)
	userMobilityConstraintUpdateCacheMut       sync.RWMutex
	userMobilityConstraintUpdateCache          = make(map[string]updateCache)
	userMobilityConstraintUpsertCacheMut       sync.RWMutex
	userMobilityConstraintUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userMobilityConstraintAfterSelectMu sync.Mutex
var userMobilityConstraintAfterSelectHooks []UserMobilityConstraintHook

var userMobilityConstraintBeforeInsertMu sync.Mutex
var userMobilityConstraintBeforeInsertHooks []UserMobilityConstraintHook
var userMobilityConstraintAfterInsertMu sync.Mutex
var userMobilityConstraintAfterInsertHooks []UserMobilityConstraintHook

var userMobilityConstraintBeforeUpdateMu sync.Mutex
var userMobilityConstraintBeforeUpdateHooks []UserMobilityConstraintHook
var userMobilityConstraintAfterUpdateMu sync.Mutex
var userMobilityConstraintAfterUpdateHooks []UserMobilityConstraintHook

var userMobilityConstraintBeforeDeleteMu sync.Mutex
var userMobilityConstraintBeforeDeleteHooks []UserMobilityConstraintHook
var userMobilityConstraintAfterDeleteMu sync.Mutex
var userMobilityConstraintAfterDeleteHooks []UserMobilityConstraintHook

var userMobilityConstraintBeforeUpsertMu sync.Mutex
var userMobilityConstraintBeforeUpsertHooks []UserMobilityConstraintHook
var userMobilityConstraintAfterUpsertMu sync.Mutex
var userMobilityConstraintAfterUpsertHooks []UserMobilityConstraintHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserMobilityConstraint) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserMobilityConstraint) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserMobilityConstraint) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserMobilityConstraint) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserMobilityConstraint) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserMobilityConstraint) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserMobilityConstraint) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserMobilityConstraint) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserMobilityConstraint) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMobilityConstraintAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserMobilityConstraintHook registers your hook function for all future operations.
func AddUserMobilityConstraintHook(hookPoint boil.HookPoint, userMobilityConstraintHook UserMobilityConstraintHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userMobilityConstraintAfterSelectMu.Lock()
		userMobilityConstraintAfterSelectHooks = append(userMobilityConstraintAfterSelectHooks, userMobilityConstraintHook)
		userMobilityConstraintAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userMobilityConstraintBeforeInsertMu.Lock()
		userMobilityConstraintBeforeInsertHooks = append(userMobilityConstraintBeforeInsertHooks, userMobilityConstraintHook)
		userMobilityConstraintBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userMobilityConstraintAfterInsertMu.Lock()
		userMobilityConstraintAfterInsertHooks = append(userMobilityConstraintAfterInsertHooks, userMobilityConstraintHook)
		userMobilityConstraintAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userMobilityConstraintBeforeUpdateMu.Lock()
		userMobilityConstraintBeforeUpdateHooks = append(userMobilityConstraintBeforeUpdateHooks, userMobilityConstraintHook)
		userMobilityConstraintBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userMobilityConstraintAfterUpdateMu.Lock()
		userMobilityConstraintAfterUpdateHooks = append(userMobilityConstraintAfterUpdateHooks, userMobilityConstraintHook)
		userMobilityConstraintAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userMobilityConstraintBeforeDeleteMu.Lock()
		userMobilityConstraintBeforeDeleteHooks = append(userMobilityConstraintBeforeDeleteHooks, userMobilityConstraintHook)
		userMobilityConstraintBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userMobilityConstraintAfterDeleteMu.Lock()
		userMobilityConstraintAfterDeleteHooks = append(userMobilityConstraintAfterDeleteHooks, userMobilityConstraintHook)
		userMobilityConstraintAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userMobilityConstraintBeforeUpsertMu.Lock()
		userMobilityConstraintBeforeUpsertHooks = append(userMobilityConstraintBeforeUpsertHooks, userMobilityConstraintHook)
		userMobilityConstraintBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userMobilityConstraintAfterUpsertMu.Lock()
		userMobilityConstraintAfterUpsertHooks = append(userMobilityConstraintAfterUpsertHooks, userMobilityConstraintHook)
		userMobilityConstraintAfterUpsertMu.Unlock()
	}
}

// One returns a single userMobilityConstraint record from the query.
func (q userMobilityConstraintQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserMobilityConstraint, error) {
	o := &UserMobilityConstraint{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for user_mobility_constraint")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserMobilityConstraint records from the query.
func (q userMobilityConstraintQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserMobilityConstraintSlice, error) {
	var o []*UserMobilityConstraint

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to UserMobilityConstraint slice")
	}

	if len(userMobilityConstraintAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserMobilityConstraint records in the query.
func (q userMobilityConstraintQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count user_mobility_constraint rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userMobilityConstraintQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if user_mobility_constraint exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserMobilityConstraint) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userMobilityConstraintL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserMobilityConstraint interface{}, mods queries.Applicator) error {
	var slice []*UserMobilityConstraint
	var object *UserMobilityConstraint

	if singular {
		var ok bool
		object, ok = maybeUserMobilityConstraint.(*UserMobilityConstraint)
		if !ok {
			object = new(UserMobilityConstraint)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserMobilityConstraint)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserMobilityConstraint))
			}
		}
	} else {
		s, ok := maybeUserMobilityConstraint.(*[]*UserMobilityConstraint)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserMobilityConstraint)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserMobilityConstraint))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userMobilityConstraintR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userMobilityConstraintR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserMobilityConstraints = append(foreign.R.UserMobilityConstraints, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserMobilityConstraints = append(foreign.R.UserMobilityConstraints, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the userMobilityConstraint to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserMobilityConstraints.
func (o *UserMobilityConstraint) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_mobility_constraint\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userMobilityConstraintPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userMobilityConstraintR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserMobilityConstraints: UserMobilityConstraintSlice{o},
		}
	} else {
		related.R.UserMobilityConstraints = append(related.R.UserMobilityConstraints, o)
	}

	return nil
}

// UserMobilityConstraints retrieves all the records using an executor.
func UserMobilityConstraints(mods ...qm.QueryMod) userMobilityConstraintQuery {
	mods = append(mods, qm.From("\"user_mobility_constraint\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_mobility_constraint\".*"})
	}

	return userMobilityConstraintQuery{q}
}

// FindUserMobilityConstraint retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserMobilityConstraint(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserMobilityConstraint, error) {
	userMobilityConstraintObj := &UserMobilityConstraint{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_mobility_constraint\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userMobilityConstraintObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from user_mobility_constraint")
	}

	if err = userMobilityConstraintObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userMobilityConstraintObj, err
	}

	return userMobilityConstraintObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserMobilityConstraint) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no user_mobility_constraint provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMobilityConstraintColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userMobilityConstraintInsertCacheMut.RLock()
	cache, cached := userMobilityConstraintInsertCache[key]
	userMobilityConstraintInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userMobilityConstraintAllColumns,
			userMobilityConstraintColumnsWithDefault,
			userMobilityConstraintColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userMobilityConstraintType, userMobilityConstraintMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userMobilityConstraintType, userMobilityConstraintMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_mobility_constraint\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_mobility_constraint\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into user_mobility_constraint")
	}

	if !cached {
		userMobilityConstraintInsertCacheMut.Lock()
		userMobilityConstraintInsertCache[key] = cache
		userMobilityConstraintInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserMobilityConstraint.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserMobilityConstraint) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userMobilityConstraintUpdateCacheMut.RLock()
	cache, cached := userMobilityConstraintUpdateCache[key]
	userMobilityConstraintUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userMobilityConstraintAllColumns,
			userMobilityConstraintPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update user_mobility_constraint, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_mobility_constraint\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userMobilityConstraintPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userMobilityConstraintType, userMobilityConstraintMapping, append(wl, userMobilityConstraintPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update user_mobility_constraint row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for user_mobility_constraint")
	}

	if !cached {
		userMobilityConstraintUpdateCacheMut.Lock()
		userMobilityConstraintUpdateCache[key] = cache
		userMobilityConstraintUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userMobilityConstraintQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for user_mobility_constraint")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for user_mobility_constraint")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserMobilityConstraintSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMobilityConstraintPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_mobility_constraint\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userMobilityConstraintPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in userMobilityConstraint slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all userMobilityConstraint")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserMobilityConstraint) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no user_mobility_constraint provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMobilityConstraintColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userMobilityConstraintUpsertCacheMut.RLock()
	cache, cached := userMobilityConstraintUpsertCache[key]
	userMobilityConstraintUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userMobilityConstraintAllColumns,
			userMobilityConstraintColumnsWithDefault,
			userMobilityConstraintColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userMobilityConstraintAllColumns,
			userMobilityConstraintPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert user_mobility_constraint, could not build update column list")
		}

		ret := strmangle.SetComplement(userMobilityConstraintAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userMobilityConstraintPrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert user_mobility_constraint, could not build conflict column list")
			}

			conflict = make([]string, len(userMobilityConstraintPrimaryKeyColumns))
			copy(conflict, userMobilityConstraintPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_mobility_constraint\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userMobilityConstraintType, userMobilityConstraintMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userMobilityConstraintType, userMobilityConstraintMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert user_mobility_constraint")
	}

	if !cached {
		userMobilityConstraintUpsertCacheMut.Lock()
		userMobilityConstraintUpsertCache[key] = cache
		userMobilityConstraintUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserMobilityConstraint record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserMobilityConstraint) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no UserMobilityConstraint provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userMobilityConstraintPrimaryKeyMapping)
	sql := "DELETE FROM \"user_mobility_constraint\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from user_mobility_constraint")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for user_mobility_constraint")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userMobilityConstraintQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no userMobilityConstraintQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from user_mobility_constraint")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for user_mobility_constraint")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserMobilityConstraintSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userMobilityConstraintBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMobilityConstraintPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_mobility_constraint\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userMobilityConstraintPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from userMobilityConstraint slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for user_mobility_constraint")
	}

	if len(userMobilityConstraintAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserMobilityConstraint) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserMobilityConstraint(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserMobilityConstraintSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserMobilityConstraintSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMobilityConstraintPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_mobility_constraint\".* FROM \"user_mobility_constraint\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userMobilityConstraintPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in UserMobilityConstraintSlice")
	}

	*o = slice

	return nil
}

// UserMobilityConstraintExists checks if the UserMobilityConstraint row exists.
func UserMobilityConstraintExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_mobility_constraint\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if user_mobility_constraint exists")
	}

	return exists, nil
}

// Exists checks if the UserMobilityConstraint row exists.
func (o *UserMobilityConstraint) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserMobilityConstraintExists(ctx, exec, o.ID)
}
