// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VenueRankingCache is an object representing the database table.
type VenueRankingCache struct {
	ID                string            `boil:"id" json:"id" toml:"id" yaml:"id"`
	DateInstanceRefID string            `boil:"date_instance_ref_id" json:"date_instance_ref_id" toml:"date_instance_ref_id" yaml:"date_instance_ref_id"`
	VenueRefID        string            `boil:"venue_ref_id" json:"venue_ref_id" toml:"venue_ref_id" yaml:"venue_ref_id"`
	RankPosition      int               `boil:"rank_position" json:"rank_position" toml:"rank_position" yaml:"rank_position"`
	RankScore         types.NullDecimal `boil:"rank_score" json:"rank_score,omitempty" toml:"rank_score" yaml:"rank_score,omitempty"`
	UserAProfileHash  null.String       `boil:"user_a_profile_hash" json:"user_a_profile_hash,omitempty" toml:"user_a_profile_hash" yaml:"user_a_profile_hash,omitempty"`
	UserBProfileHash  null.String       `boil:"user_b_profile_hash" json:"user_b_profile_hash,omitempty" toml:"user_b_profile_hash" yaml:"user_b_profile_hash,omitempty"`
	CreatedAt         time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt         null.Time         `boil:"expires_at" json:"expires_at,omitempty" toml:"expires_at" yaml:"expires_at,omitempty"`

	R *venueRankingCacheR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L venueRankingCacheL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VenueRankingCacheColumns = struct {
	ID                string
	DateInstanceRefID string
	VenueRefID        string
	RankPosition      string
	RankScore         string
	UserAProfileHash  string
	UserBProfileHash  string
	CreatedAt         string
	ExpiresAt         string
}{
	ID:                "id",
	DateInstanceRefID: "date_instance_ref_id",
	VenueRefID:        "venue_ref_id",
	RankPosition:      "rank_position",
	RankScore:         "rank_score",
	UserAProfileHash:  "user_a_profile_hash",
	UserBProfileHash:  "user_b_profile_hash",
	CreatedAt:         "created_at",
	ExpiresAt:         "expires_at",
}

var VenueRankingCacheTableColumns = struct {
	ID                string
	DateInstanceRefID string
	VenueRefID        string
	RankPosition      string
	RankScore         string
	UserAProfileHash  string
	UserBProfileHash  string
	CreatedAt         string
	ExpiresAt         string
}{
	ID:                "venue_ranking_cache.id",
	DateInstanceRefID: "venue_ranking_cache.date_instance_ref_id",
	VenueRefID:        "venue_ranking_cache.venue_ref_id",
	RankPosition:      "venue_ranking_cache.rank_position",
	RankScore:         "venue_ranking_cache.rank_score",
	UserAProfileHash:  "venue_ranking_cache.user_a_profile_hash",
	UserBProfileHash:  "venue_ranking_cache.user_b_profile_hash",
	CreatedAt:         "venue_ranking_cache.created_at",
	ExpiresAt:         "venue_ranking_cache.expires_at",
}

// Generated where

var VenueRankingCacheWhere = struct {
	ID                whereHelperstring
	DateInstanceRefID whereHelperstring
	VenueRefID        whereHelperstring
	RankPosition      whereHelperint
	RankScore         whereHelpertypes_NullDecimal
	UserAProfileHash  whereHelpernull_String
	UserBProfileHash  whereHelpernull_String
	CreatedAt         whereHelpertime_Time
	ExpiresAt         whereHelpernull_Time
}{
	ID:                whereHelperstring{field: "\"venue_ranking_cache\".\"id\""},
	DateInstanceRefID: whereHelperstring{field: "\"venue_ranking_cache\".\"date_instance_ref_id\""},
	VenueRefID:        whereHelperstring{field: "\"venue_ranking_cache\".\"venue_ref_id\""},
	RankPosition:      whereHelperint{field: "\"venue_ranking_cache\".\"rank_position\""},
	RankScore:         whereHelpertypes_NullDecimal{field: "\"venue_ranking_cache\".\"rank_score\""},
	UserAProfileHash:  whereHelpernull_String{field: "\"venue_ranking_cache\".\"user_a_profile_hash\""},
	UserBProfileHash:  whereHelpernull_String{field: "\"venue_ranking_cache\".\"user_b_profile_hash\""},
	CreatedAt:         whereHelpertime_Time{field: "\"venue_ranking_cache\".\"created_at\""},
	ExpiresAt:         whereHelpernull_Time{field: "\"venue_ranking_cache\".\"expires_at\""},
}

// VenueRankingCacheRels is where relationship names are stored.
var VenueRankingCacheRels = struct {
	DateInstanceRef string
	VenueRef        string
}{
	DateInstanceRef: "DateInstanceRef",
	VenueRef:        "VenueRef",
}

// venueRankingCacheR is where relationships are stored.
type venueRankingCacheR struct {
	DateInstanceRef *DateInstance `boil:"DateInstanceRef" json:"DateInstanceRef" toml:"DateInstanceRef" yaml:"DateInstanceRef"`
	VenueRef        *Venue        `boil:"VenueRef" json:"VenueRef" toml:"VenueRef" yaml:"VenueRef"`
}

// NewStruct creates a new relationship struct
func (*venueRankingCacheR) NewStruct() *venueRankingCacheR {
	return &venueRankingCacheR{}
}

func (o *VenueRankingCache) GetDateInstanceRef() *DateInstance {
	if o == nil {
		return nil
	}

	return o.R.GetDateInstanceRef()
}

func (r *venueRankingCacheR) GetDateInstanceRef() *DateInstance {
	if r == nil {
		return nil
	}

	return r.DateInstanceRef
}

func (o *VenueRankingCache) GetVenueRef() *Venue {
	if o == nil {
		return nil
	}

	return o.R.GetVenueRef()
}

func (r *venueRankingCacheR) GetVenueRef() *Venue {
	if r == nil {
		return nil
	}

	return r.VenueRef
}

// venueRankingCacheL is where Load methods for each relationship are stored.
type venueRankingCacheL struct{}

var (
	venueRankingCacheAllColumns            = []string{"id", "date_instance_ref_id", "venue_ref_id", "rank_position", "rank_score", "user_a_profile_hash", "user_b_profile_hash", "created_at", "expires_at"}
	venueRankingCacheColumnsWithoutDefault = []string{"date_instance_ref_id", "venue_ref_id", "rank_position"}
	venueRankingCacheColumnsWithDefault    = []string{"id", "rank_score", "user_a_profile_hash", "user_b_profile_hash", "created_at", "expires_at"}
	venueRankingCachePrimaryKeyColumns     = []string{"id"}
	venueRankingCacheGeneratedColumns      = []string{}
)

type (
	// VenueRankingCacheSlice is an alias for a slice of pointers to VenueRankingCache.
	// This should almost always be used instead of []VenueRankingCache.
	VenueRankingCacheSlice []*VenueRankingCache
	// VenueRankingCacheHook is the signature for custom VenueRankingCache hook methods
	VenueRankingCacheHook func(context.Context, boil.ContextExecutor, *VenueRankingCache) error

	venueRankingCacheQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	venueRankingCacheType                 = reflect.TypeOf(&VenueRankingCache{})
	venueRankingCacheMapping              = queries.MakeStructMapping(venueRankingCacheType)
	venueRankingCachePrimaryKeyMapping, _ = queries.BindMapping(venueRankingCacheType, venueRankingCacheMapping, venueRankingCachePrimaryKeyColumns)
	venueRankingCacheInsertCacheMut       sync.RWMutex
	venueRankingCacheInsertCache          = make(map[string]insertCache)
	venueRankingCacheUpdateCacheMut       sync.RWMutex
	venueRankingCacheUpdateCache          = make(map[string]updateCache)
	venueRankingCacheUpsertCacheMut       sync.RWMutex
	venueRankingCacheUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var venueRankingCacheAfterSelectMu sync.Mutex
var venueRankingCacheAfterSelectHooks []VenueRankingCacheHook

var venueRankingCacheBeforeInsertMu sync.Mutex
var venueRankingCacheBeforeInsertHooks []VenueRankingCacheHook
var venueRankingCacheAfterInsertMu sync.Mutex
var venueRankingCacheAfterInsertHooks []VenueRankingCacheHook

var venueRankingCacheBeforeUpdateMu sync.Mutex
var venueRankingCacheBeforeUpdateHooks []VenueRankingCacheHook
var venueRankingCacheAfterUpdateMu sync.Mutex
var venueRankingCacheAfterUpdateHooks []VenueRankingCacheHook

var venueRankingCacheBeforeDeleteMu sync.Mutex
var venueRankingCacheBeforeDeleteHooks []VenueRankingCacheHook
var venueRankingCacheAfterDeleteMu sync.Mutex
var venueRankingCacheAfterDeleteHooks []VenueRankingCacheHook

var venueRankingCacheBeforeUpsertMu sync.Mutex
var venueRankingCacheBeforeUpsertHooks []VenueRankingCacheHook
var venueRankingCacheAfterUpsertMu sync.Mutex
var venueRankingCacheAfterUpsertHooks []VenueRankingCacheHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VenueRankingCache) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VenueRankingCache) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VenueRankingCache) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VenueRankingCache) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VenueRankingCache) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VenueRankingCache) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VenueRankingCache) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VenueRankingCache) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VenueRankingCache) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range venueRankingCacheAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVenueRankingCacheHook registers your hook function for all future operations.
func AddVenueRankingCacheHook(hookPoint boil.HookPoint, venueRankingCacheHook VenueRankingCacheHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		venueRankingCacheAfterSelectMu.Lock()
		venueRankingCacheAfterSelectHooks = append(venueRankingCacheAfterSelectHooks, venueRankingCacheHook)
		venueRankingCacheAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		venueRankingCacheBeforeInsertMu.Lock()
		venueRankingCacheBeforeInsertHooks = append(venueRankingCacheBeforeInsertHooks, venueRankingCacheHook)
		venueRankingCacheBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		venueRankingCacheAfterInsertMu.Lock()
		venueRankingCacheAfterInsertHooks = append(venueRankingCacheAfterInsertHooks, venueRankingCacheHook)
		venueRankingCacheAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		venueRankingCacheBeforeUpdateMu.Lock()
		venueRankingCacheBeforeUpdateHooks = append(venueRankingCacheBeforeUpdateHooks, venueRankingCacheHook)
		venueRankingCacheBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		venueRankingCacheAfterUpdateMu.Lock()
		venueRankingCacheAfterUpdateHooks = append(venueRankingCacheAfterUpdateHooks, venueRankingCacheHook)
		venueRankingCacheAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		venueRankingCacheBeforeDeleteMu.Lock()
		venueRankingCacheBeforeDeleteHooks = append(venueRankingCacheBeforeDeleteHooks, venueRankingCacheHook)
		venueRankingCacheBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		venueRankingCacheAfterDeleteMu.Lock()
		venueRankingCacheAfterDeleteHooks = append(venueRankingCacheAfterDeleteHooks, venueRankingCacheHook)
		venueRankingCacheAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		venueRankingCacheBeforeUpsertMu.Lock()
		venueRankingCacheBeforeUpsertHooks = append(venueRankingCacheBeforeUpsertHooks, venueRankingCacheHook)
		venueRankingCacheBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		venueRankingCacheAfterUpsertMu.Lock()
		venueRankingCacheAfterUpsertHooks = append(venueRankingCacheAfterUpsertHooks, venueRankingCacheHook)
		venueRankingCacheAfterUpsertMu.Unlock()
	}
}

// One returns a single venueRankingCache record from the query.
func (q venueRankingCacheQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VenueRankingCache, error) {
	o := &VenueRankingCache{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for venue_ranking_cache")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VenueRankingCache records from the query.
func (q venueRankingCacheQuery) All(ctx context.Context, exec boil.ContextExecutor) (VenueRankingCacheSlice, error) {
	var o []*VenueRankingCache

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to VenueRankingCache slice")
	}

	if len(venueRankingCacheAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VenueRankingCache records in the query.
func (q venueRankingCacheQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count venue_ranking_cache rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q venueRankingCacheQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if venue_ranking_cache exists")
	}

	return count > 0, nil
}

// DateInstanceRef pointed to by the foreign key.
func (o *VenueRankingCache) DateInstanceRef(mods ...qm.QueryMod) dateInstanceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DateInstanceRefID),
	}

	queryMods = append(queryMods, mods...)

	return DateInstances(queryMods...)
}

// VenueRef pointed to by the foreign key.
func (o *VenueRankingCache) VenueRef(mods ...qm.QueryMod) venueQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.VenueRefID),
	}

	queryMods = append(queryMods, mods...)

	return Venues(queryMods...)
}

// LoadDateInstanceRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (venueRankingCacheL) LoadDateInstanceRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVenueRankingCache interface{}, mods queries.Applicator) error {
	var slice []*VenueRankingCache
	var object *VenueRankingCache

	if singular {
		var ok bool
		object, ok = maybeVenueRankingCache.(*VenueRankingCache)
		if !ok {
			object = new(VenueRankingCache)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVenueRankingCache)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVenueRankingCache))
			}
		}
	} else {
		s, ok := maybeVenueRankingCache.(*[]*VenueRankingCache)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVenueRankingCache)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVenueRankingCache))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &venueRankingCacheR{}
		}
		args[object.DateInstanceRefID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &venueRankingCacheR{}
			}

			args[obj.DateInstanceRefID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`date_instance`),
		qm.WhereIn(`date_instance.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DateInstance")
	}

	var resultSlice []*DateInstance
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DateInstance")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for date_instance")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for date_instance")
	}

	if len(dateInstanceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DateInstanceRef = foreign
		if foreign.R == nil {
			foreign.R = &dateInstanceR{}
		}
		foreign.R.DateInstanceRefVenueRankingCaches = append(foreign.R.DateInstanceRefVenueRankingCaches, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DateInstanceRefID == foreign.ID {
				local.R.DateInstanceRef = foreign
				if foreign.R == nil {
					foreign.R = &dateInstanceR{}
				}
				foreign.R.DateInstanceRefVenueRankingCaches = append(foreign.R.DateInstanceRefVenueRankingCaches, local)
				break
			}
		}
	}

	return nil
}

// LoadVenueRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (venueRankingCacheL) LoadVenueRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVenueRankingCache interface{}, mods queries.Applicator) error {
	var slice []*VenueRankingCache
	var object *VenueRankingCache

	if singular {
		var ok bool
		object, ok = maybeVenueRankingCache.(*VenueRankingCache)
		if !ok {
			object = new(VenueRankingCache)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVenueRankingCache)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVenueRankingCache))
			}
		}
	} else {
		s, ok := maybeVenueRankingCache.(*[]*VenueRankingCache)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVenueRankingCache)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVenueRankingCache))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &venueRankingCacheR{}
		}
		args[object.VenueRefID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &venueRankingCacheR{}
			}

			args[obj.VenueRefID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`venue`),
		qm.WhereIn(`venue.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Venue")
	}

	var resultSlice []*Venue
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Venue")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for venue")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for venue")
	}

	if len(venueAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.VenueRef = foreign
		if foreign.R == nil {
			foreign.R = &venueR{}
		}
		foreign.R.VenueRefVenueRankingCaches = append(foreign.R.VenueRefVenueRankingCaches, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.VenueRefID == foreign.ID {
				local.R.VenueRef = foreign
				if foreign.R == nil {
					foreign.R = &venueR{}
				}
				foreign.R.VenueRefVenueRankingCaches = append(foreign.R.VenueRefVenueRankingCaches, local)
				break
			}
		}
	}

	return nil
}

// SetDateInstanceRef of the venueRankingCache to the related item.
// Sets o.R.DateInstanceRef to related.
// Adds o to related.R.DateInstanceRefVenueRankingCaches.
func (o *VenueRankingCache) SetDateInstanceRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DateInstance) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"venue_ranking_cache\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"date_instance_ref_id"}),
		strmangle.WhereClause("\"", "\"", 2, venueRankingCachePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DateInstanceRefID = related.ID
	if o.R == nil {
		o.R = &venueRankingCacheR{
			DateInstanceRef: related,
		}
	} else {
		o.R.DateInstanceRef = related
	}

	if related.R == nil {
		related.R = &dateInstanceR{
			DateInstanceRefVenueRankingCaches: VenueRankingCacheSlice{o},
		}
	} else {
		related.R.DateInstanceRefVenueRankingCaches = append(related.R.DateInstanceRefVenueRankingCaches, o)
	}

	return nil
}

// SetVenueRef of the venueRankingCache to the related item.
// Sets o.R.VenueRef to related.
// Adds o to related.R.VenueRefVenueRankingCaches.
func (o *VenueRankingCache) SetVenueRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Venue) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"venue_ranking_cache\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"venue_ref_id"}),
		strmangle.WhereClause("\"", "\"", 2, venueRankingCachePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.VenueRefID = related.ID
	if o.R == nil {
		o.R = &venueRankingCacheR{
			VenueRef: related,
		}
	} else {
		o.R.VenueRef = related
	}

	if related.R == nil {
		related.R = &venueR{
			VenueRefVenueRankingCaches: VenueRankingCacheSlice{o},
		}
	} else {
		related.R.VenueRefVenueRankingCaches = append(related.R.VenueRefVenueRankingCaches, o)
	}

	return nil
}

// VenueRankingCaches retrieves all the records using an executor.
func VenueRankingCaches(mods ...qm.QueryMod) venueRankingCacheQuery {
	mods = append(mods, qm.From("\"venue_ranking_cache\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"venue_ranking_cache\".*"})
	}

	return venueRankingCacheQuery{q}
}

// FindVenueRankingCache retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVenueRankingCache(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*VenueRankingCache, error) {
	venueRankingCacheObj := &VenueRankingCache{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"venue_ranking_cache\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, venueRankingCacheObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from venue_ranking_cache")
	}

	if err = venueRankingCacheObj.doAfterSelectHooks(ctx, exec); err != nil {
		return venueRankingCacheObj, err
	}

	return venueRankingCacheObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VenueRankingCache) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no venue_ranking_cache provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(venueRankingCacheColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	venueRankingCacheInsertCacheMut.RLock()
	cache, cached := venueRankingCacheInsertCache[key]
	venueRankingCacheInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			venueRankingCacheAllColumns,
			venueRankingCacheColumnsWithDefault,
			venueRankingCacheColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(venueRankingCacheType, venueRankingCacheMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(venueRankingCacheType, venueRankingCacheMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"venue_ranking_cache\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"venue_ranking_cache\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into venue_ranking_cache")
	}

	if !cached {
		venueRankingCacheInsertCacheMut.Lock()
		venueRankingCacheInsertCache[key] = cache
		venueRankingCacheInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the VenueRankingCache.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VenueRankingCache) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	venueRankingCacheUpdateCacheMut.RLock()
	cache, cached := venueRankingCacheUpdateCache[key]
	venueRankingCacheUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			venueRankingCacheAllColumns,
			venueRankingCachePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update venue_ranking_cache, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"venue_ranking_cache\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, venueRankingCachePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(venueRankingCacheType, venueRankingCacheMapping, append(wl, venueRankingCachePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update venue_ranking_cache row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for venue_ranking_cache")
	}

	if !cached {
		venueRankingCacheUpdateCacheMut.Lock()
		venueRankingCacheUpdateCache[key] = cache
		venueRankingCacheUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q venueRankingCacheQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for venue_ranking_cache")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for venue_ranking_cache")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VenueRankingCacheSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), venueRankingCachePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"venue_ranking_cache\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, venueRankingCachePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in venueRankingCache slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all venueRankingCache")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VenueRankingCache) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no venue_ranking_cache provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(venueRankingCacheColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	venueRankingCacheUpsertCacheMut.RLock()
	cache, cached := venueRankingCacheUpsertCache[key]
	venueRankingCacheUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			venueRankingCacheAllColumns,
			venueRankingCacheColumnsWithDefault,
			venueRankingCacheColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			venueRankingCacheAllColumns,
			venueRankingCachePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert venue_ranking_cache, could not build update column list")
		}

		ret := strmangle.SetComplement(venueRankingCacheAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(venueRankingCachePrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert venue_ranking_cache, could not build conflict column list")
			}

			conflict = make([]string, len(venueRankingCachePrimaryKeyColumns))
			copy(conflict, venueRankingCachePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"venue_ranking_cache\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(venueRankingCacheType, venueRankingCacheMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(venueRankingCacheType, venueRankingCacheMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert venue_ranking_cache")
	}

	if !cached {
		venueRankingCacheUpsertCacheMut.Lock()
		venueRankingCacheUpsertCache[key] = cache
		venueRankingCacheUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single VenueRankingCache record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VenueRankingCache) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no VenueRankingCache provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), venueRankingCachePrimaryKeyMapping)
	sql := "DELETE FROM \"venue_ranking_cache\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from venue_ranking_cache")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for venue_ranking_cache")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q venueRankingCacheQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no venueRankingCacheQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from venue_ranking_cache")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for venue_ranking_cache")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VenueRankingCacheSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(venueRankingCacheBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), venueRankingCachePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"venue_ranking_cache\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, venueRankingCachePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from venueRankingCache slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for venue_ranking_cache")
	}

	if len(venueRankingCacheAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VenueRankingCache) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVenueRankingCache(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VenueRankingCacheSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VenueRankingCacheSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), venueRankingCachePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"venue_ranking_cache\".* FROM \"venue_ranking_cache\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, venueRankingCachePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in VenueRankingCacheSlice")
	}

	*o = slice

	return nil
}

// VenueRankingCacheExists checks if the VenueRankingCache row exists.
func VenueRankingCacheExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"venue_ranking_cache\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if venue_ranking_cache exists")
	}

	return exists, nil
}

// Exists checks if the VenueRankingCache row exists.
func (o *VenueRankingCache) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VenueRankingCacheExists(ctx, exec, o.ID)
}
