// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WingsEcnActionLog is an object representing the database table.
type WingsEcnActionLog struct {
	ID             string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserRefID      string    `boil:"user_ref_id" json:"user_ref_id" toml:"user_ref_id" yaml:"user_ref_id"`
	ActionLogType  string    `boil:"action_log_type" json:"action_log_type" toml:"action_log_type" yaml:"action_log_type"`
	ExtDomainRefID string    `boil:"ext_domain_ref_id" json:"ext_domain_ref_id" toml:"ext_domain_ref_id" yaml:"ext_domain_ref_id"`
	IsCredit       bool      `boil:"is_credit" json:"is_credit" toml:"is_credit" yaml:"is_credit"`
	ExtraInfo      null.JSON `boil:"extra_info" json:"extra_info,omitempty" toml:"extra_info" yaml:"extra_info,omitempty"`
	IsActive       null.Int  `boil:"is_active" json:"is_active,omitempty" toml:"is_active" yaml:"is_active,omitempty"`
	CreatedBy      null.Int  `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	CreatedDate    null.Time `boil:"created_date" json:"created_date,omitempty" toml:"created_date" yaml:"created_date,omitempty"`
	LastUpdated    null.Time `boil:"last_updated" json:"last_updated,omitempty" toml:"last_updated" yaml:"last_updated,omitempty"`
	UpdatedBy      null.Int  `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`

	R *wingsEcnActionLogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L wingsEcnActionLogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WingsEcnActionLogColumns = struct {
	ID             string
	UserRefID      string
	ActionLogType  string
	ExtDomainRefID string
	IsCredit       string
	ExtraInfo      string
	IsActive       string
	CreatedBy      string
	CreatedDate    string
	LastUpdated    string
	UpdatedBy      string
}{
	ID:             "id",
	UserRefID:      "user_ref_id",
	ActionLogType:  "action_log_type",
	ExtDomainRefID: "ext_domain_ref_id",
	IsCredit:       "is_credit",
	ExtraInfo:      "extra_info",
	IsActive:       "is_active",
	CreatedBy:      "created_by",
	CreatedDate:    "created_date",
	LastUpdated:    "last_updated",
	UpdatedBy:      "updated_by",
}

var WingsEcnActionLogTableColumns = struct {
	ID             string
	UserRefID      string
	ActionLogType  string
	ExtDomainRefID string
	IsCredit       string
	ExtraInfo      string
	IsActive       string
	CreatedBy      string
	CreatedDate    string
	LastUpdated    string
	UpdatedBy      string
}{
	ID:             "wings_ecn_action_log.id",
	UserRefID:      "wings_ecn_action_log.user_ref_id",
	ActionLogType:  "wings_ecn_action_log.action_log_type",
	ExtDomainRefID: "wings_ecn_action_log.ext_domain_ref_id",
	IsCredit:       "wings_ecn_action_log.is_credit",
	ExtraInfo:      "wings_ecn_action_log.extra_info",
	IsActive:       "wings_ecn_action_log.is_active",
	CreatedBy:      "wings_ecn_action_log.created_by",
	CreatedDate:    "wings_ecn_action_log.created_date",
	LastUpdated:    "wings_ecn_action_log.last_updated",
	UpdatedBy:      "wings_ecn_action_log.updated_by",
}

// Generated where

var WingsEcnActionLogWhere = struct {
	ID             whereHelperstring
	UserRefID      whereHelperstring
	ActionLogType  whereHelperstring
	ExtDomainRefID whereHelperstring
	IsCredit       whereHelperbool
	ExtraInfo      whereHelpernull_JSON
	IsActive       whereHelpernull_Int
	CreatedBy      whereHelpernull_Int
	CreatedDate    whereHelpernull_Time
	LastUpdated    whereHelpernull_Time
	UpdatedBy      whereHelpernull_Int
}{
	ID:             whereHelperstring{field: "\"wings_ecn_action_log\".\"id\""},
	UserRefID:      whereHelperstring{field: "\"wings_ecn_action_log\".\"user_ref_id\""},
	ActionLogType:  whereHelperstring{field: "\"wings_ecn_action_log\".\"action_log_type\""},
	ExtDomainRefID: whereHelperstring{field: "\"wings_ecn_action_log\".\"ext_domain_ref_id\""},
	IsCredit:       whereHelperbool{field: "\"wings_ecn_action_log\".\"is_credit\""},
	ExtraInfo:      whereHelpernull_JSON{field: "\"wings_ecn_action_log\".\"extra_info\""},
	IsActive:       whereHelpernull_Int{field: "\"wings_ecn_action_log\".\"is_active\""},
	CreatedBy:      whereHelpernull_Int{field: "\"wings_ecn_action_log\".\"created_by\""},
	CreatedDate:    whereHelpernull_Time{field: "\"wings_ecn_action_log\".\"created_date\""},
	LastUpdated:    whereHelpernull_Time{field: "\"wings_ecn_action_log\".\"last_updated\""},
	UpdatedBy:      whereHelpernull_Int{field: "\"wings_ecn_action_log\".\"updated_by\""},
}

// WingsEcnActionLogRels is where relationship names are stored.
var WingsEcnActionLogRels = struct {
	UserRef                          string
	ActionLogRefWingsEcnTransactions string
}{
	UserRef:                          "UserRef",
	ActionLogRefWingsEcnTransactions: "ActionLogRefWingsEcnTransactions",
}

// wingsEcnActionLogR is where relationships are stored.
type wingsEcnActionLogR struct {
	UserRef                          *User                    `boil:"UserRef" json:"UserRef" toml:"UserRef" yaml:"UserRef"`
	ActionLogRefWingsEcnTransactions WingsEcnTransactionSlice `boil:"ActionLogRefWingsEcnTransactions" json:"ActionLogRefWingsEcnTransactions" toml:"ActionLogRefWingsEcnTransactions" yaml:"ActionLogRefWingsEcnTransactions"`
}

// NewStruct creates a new relationship struct
func (*wingsEcnActionLogR) NewStruct() *wingsEcnActionLogR {
	return &wingsEcnActionLogR{}
}

func (o *WingsEcnActionLog) GetUserRef() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUserRef()
}

func (r *wingsEcnActionLogR) GetUserRef() *User {
	if r == nil {
		return nil
	}

	return r.UserRef
}

func (o *WingsEcnActionLog) GetActionLogRefWingsEcnTransactions() WingsEcnTransactionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetActionLogRefWingsEcnTransactions()
}

func (r *wingsEcnActionLogR) GetActionLogRefWingsEcnTransactions() WingsEcnTransactionSlice {
	if r == nil {
		return nil
	}

	return r.ActionLogRefWingsEcnTransactions
}

// wingsEcnActionLogL is where Load methods for each relationship are stored.
type wingsEcnActionLogL struct{}

var (
	wingsEcnActionLogAllColumns            = []string{"id", "user_ref_id", "action_log_type", "ext_domain_ref_id", "is_credit", "extra_info", "is_active", "created_by", "created_date", "last_updated", "updated_by"}
	wingsEcnActionLogColumnsWithoutDefault = []string{"user_ref_id", "action_log_type", "ext_domain_ref_id", "is_credit"}
	wingsEcnActionLogColumnsWithDefault    = []string{"id", "extra_info", "is_active", "created_by", "created_date", "last_updated", "updated_by"}
	wingsEcnActionLogPrimaryKeyColumns     = []string{"id"}
	wingsEcnActionLogGeneratedColumns      = []string{}
)

type (
	// WingsEcnActionLogSlice is an alias for a slice of pointers to WingsEcnActionLog.
	// This should almost always be used instead of []WingsEcnActionLog.
	WingsEcnActionLogSlice []*WingsEcnActionLog
	// WingsEcnActionLogHook is the signature for custom WingsEcnActionLog hook methods
	WingsEcnActionLogHook func(context.Context, boil.ContextExecutor, *WingsEcnActionLog) error

	wingsEcnActionLogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	wingsEcnActionLogType                 = reflect.TypeOf(&WingsEcnActionLog{})
	wingsEcnActionLogMapping              = queries.MakeStructMapping(wingsEcnActionLogType)
	wingsEcnActionLogPrimaryKeyMapping, _ = queries.BindMapping(wingsEcnActionLogType, wingsEcnActionLogMapping, wingsEcnActionLogPrimaryKeyColumns)
	wingsEcnActionLogInsertCacheMut       sync.RWMutex
	wingsEcnActionLogInsertCache          = make(map[string]insertCache)
	wingsEcnActionLogUpdateCacheMut       sync.RWMutex
	wingsEcnActionLogUpdateCache          = make(map[string]updateCache)
	wingsEcnActionLogUpsertCacheMut       sync.RWMutex
	wingsEcnActionLogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var wingsEcnActionLogAfterSelectMu sync.Mutex
var wingsEcnActionLogAfterSelectHooks []WingsEcnActionLogHook

var wingsEcnActionLogBeforeInsertMu sync.Mutex
var wingsEcnActionLogBeforeInsertHooks []WingsEcnActionLogHook
var wingsEcnActionLogAfterInsertMu sync.Mutex
var wingsEcnActionLogAfterInsertHooks []WingsEcnActionLogHook

var wingsEcnActionLogBeforeUpdateMu sync.Mutex
var wingsEcnActionLogBeforeUpdateHooks []WingsEcnActionLogHook
var wingsEcnActionLogAfterUpdateMu sync.Mutex
var wingsEcnActionLogAfterUpdateHooks []WingsEcnActionLogHook

var wingsEcnActionLogBeforeDeleteMu sync.Mutex
var wingsEcnActionLogBeforeDeleteHooks []WingsEcnActionLogHook
var wingsEcnActionLogAfterDeleteMu sync.Mutex
var wingsEcnActionLogAfterDeleteHooks []WingsEcnActionLogHook

var wingsEcnActionLogBeforeUpsertMu sync.Mutex
var wingsEcnActionLogBeforeUpsertHooks []WingsEcnActionLogHook
var wingsEcnActionLogAfterUpsertMu sync.Mutex
var wingsEcnActionLogAfterUpsertHooks []WingsEcnActionLogHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WingsEcnActionLog) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WingsEcnActionLog) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WingsEcnActionLog) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WingsEcnActionLog) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WingsEcnActionLog) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WingsEcnActionLog) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WingsEcnActionLog) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WingsEcnActionLog) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WingsEcnActionLog) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnActionLogAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWingsEcnActionLogHook registers your hook function for all future operations.
func AddWingsEcnActionLogHook(hookPoint boil.HookPoint, wingsEcnActionLogHook WingsEcnActionLogHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		wingsEcnActionLogAfterSelectMu.Lock()
		wingsEcnActionLogAfterSelectHooks = append(wingsEcnActionLogAfterSelectHooks, wingsEcnActionLogHook)
		wingsEcnActionLogAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		wingsEcnActionLogBeforeInsertMu.Lock()
		wingsEcnActionLogBeforeInsertHooks = append(wingsEcnActionLogBeforeInsertHooks, wingsEcnActionLogHook)
		wingsEcnActionLogBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		wingsEcnActionLogAfterInsertMu.Lock()
		wingsEcnActionLogAfterInsertHooks = append(wingsEcnActionLogAfterInsertHooks, wingsEcnActionLogHook)
		wingsEcnActionLogAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		wingsEcnActionLogBeforeUpdateMu.Lock()
		wingsEcnActionLogBeforeUpdateHooks = append(wingsEcnActionLogBeforeUpdateHooks, wingsEcnActionLogHook)
		wingsEcnActionLogBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		wingsEcnActionLogAfterUpdateMu.Lock()
		wingsEcnActionLogAfterUpdateHooks = append(wingsEcnActionLogAfterUpdateHooks, wingsEcnActionLogHook)
		wingsEcnActionLogAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		wingsEcnActionLogBeforeDeleteMu.Lock()
		wingsEcnActionLogBeforeDeleteHooks = append(wingsEcnActionLogBeforeDeleteHooks, wingsEcnActionLogHook)
		wingsEcnActionLogBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		wingsEcnActionLogAfterDeleteMu.Lock()
		wingsEcnActionLogAfterDeleteHooks = append(wingsEcnActionLogAfterDeleteHooks, wingsEcnActionLogHook)
		wingsEcnActionLogAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		wingsEcnActionLogBeforeUpsertMu.Lock()
		wingsEcnActionLogBeforeUpsertHooks = append(wingsEcnActionLogBeforeUpsertHooks, wingsEcnActionLogHook)
		wingsEcnActionLogBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		wingsEcnActionLogAfterUpsertMu.Lock()
		wingsEcnActionLogAfterUpsertHooks = append(wingsEcnActionLogAfterUpsertHooks, wingsEcnActionLogHook)
		wingsEcnActionLogAfterUpsertMu.Unlock()
	}
}

// One returns a single wingsEcnActionLog record from the query.
func (q wingsEcnActionLogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WingsEcnActionLog, error) {
	o := &WingsEcnActionLog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for wings_ecn_action_log")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WingsEcnActionLog records from the query.
func (q wingsEcnActionLogQuery) All(ctx context.Context, exec boil.ContextExecutor) (WingsEcnActionLogSlice, error) {
	var o []*WingsEcnActionLog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to WingsEcnActionLog slice")
	}

	if len(wingsEcnActionLogAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WingsEcnActionLog records in the query.
func (q wingsEcnActionLogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count wings_ecn_action_log rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q wingsEcnActionLogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if wings_ecn_action_log exists")
	}

	return count > 0, nil
}

// UserRef pointed to by the foreign key.
func (o *WingsEcnActionLog) UserRef(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserRefID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// ActionLogRefWingsEcnTransactions retrieves all the wings_ecn_transaction's WingsEcnTransactions with an executor via action_log_ref_id column.
func (o *WingsEcnActionLog) ActionLogRefWingsEcnTransactions(mods ...qm.QueryMod) wingsEcnTransactionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"wings_ecn_transaction\".\"action_log_ref_id\"=?", o.ID),
	)

	return WingsEcnTransactions(queryMods...)
}

// LoadUserRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (wingsEcnActionLogL) LoadUserRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWingsEcnActionLog interface{}, mods queries.Applicator) error {
	var slice []*WingsEcnActionLog
	var object *WingsEcnActionLog

	if singular {
		var ok bool
		object, ok = maybeWingsEcnActionLog.(*WingsEcnActionLog)
		if !ok {
			object = new(WingsEcnActionLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWingsEcnActionLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWingsEcnActionLog))
			}
		}
	} else {
		s, ok := maybeWingsEcnActionLog.(*[]*WingsEcnActionLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWingsEcnActionLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWingsEcnActionLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &wingsEcnActionLogR{}
		}
		args[object.UserRefID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &wingsEcnActionLogR{}
			}

			args[obj.UserRefID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UserRef = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserRefWingsEcnActionLogs = append(foreign.R.UserRefWingsEcnActionLogs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserRefID == foreign.ID {
				local.R.UserRef = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserRefWingsEcnActionLogs = append(foreign.R.UserRefWingsEcnActionLogs, local)
				break
			}
		}
	}

	return nil
}

// LoadActionLogRefWingsEcnTransactions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (wingsEcnActionLogL) LoadActionLogRefWingsEcnTransactions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWingsEcnActionLog interface{}, mods queries.Applicator) error {
	var slice []*WingsEcnActionLog
	var object *WingsEcnActionLog

	if singular {
		var ok bool
		object, ok = maybeWingsEcnActionLog.(*WingsEcnActionLog)
		if !ok {
			object = new(WingsEcnActionLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWingsEcnActionLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWingsEcnActionLog))
			}
		}
	} else {
		s, ok := maybeWingsEcnActionLog.(*[]*WingsEcnActionLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWingsEcnActionLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWingsEcnActionLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &wingsEcnActionLogR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &wingsEcnActionLogR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`wings_ecn_transaction`),
		qm.WhereIn(`wings_ecn_transaction.action_log_ref_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load wings_ecn_transaction")
	}

	var resultSlice []*WingsEcnTransaction
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice wings_ecn_transaction")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on wings_ecn_transaction")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for wings_ecn_transaction")
	}

	if len(wingsEcnTransactionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ActionLogRefWingsEcnTransactions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &wingsEcnTransactionR{}
			}
			foreign.R.ActionLogRef = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ActionLogRefID {
				local.R.ActionLogRefWingsEcnTransactions = append(local.R.ActionLogRefWingsEcnTransactions, foreign)
				if foreign.R == nil {
					foreign.R = &wingsEcnTransactionR{}
				}
				foreign.R.ActionLogRef = local
				break
			}
		}
	}

	return nil
}

// SetUserRef of the wingsEcnActionLog to the related item.
// Sets o.R.UserRef to related.
// Adds o to related.R.UserRefWingsEcnActionLogs.
func (o *WingsEcnActionLog) SetUserRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"wings_ecn_action_log\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_ref_id"}),
		strmangle.WhereClause("\"", "\"", 2, wingsEcnActionLogPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserRefID = related.ID
	if o.R == nil {
		o.R = &wingsEcnActionLogR{
			UserRef: related,
		}
	} else {
		o.R.UserRef = related
	}

	if related.R == nil {
		related.R = &userR{
			UserRefWingsEcnActionLogs: WingsEcnActionLogSlice{o},
		}
	} else {
		related.R.UserRefWingsEcnActionLogs = append(related.R.UserRefWingsEcnActionLogs, o)
	}

	return nil
}

// AddActionLogRefWingsEcnTransactions adds the given related objects to the existing relationships
// of the wings_ecn_action_log, optionally inserting them as new records.
// Appends related to o.R.ActionLogRefWingsEcnTransactions.
// Sets related.R.ActionLogRef appropriately.
func (o *WingsEcnActionLog) AddActionLogRefWingsEcnTransactions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WingsEcnTransaction) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ActionLogRefID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"wings_ecn_transaction\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"action_log_ref_id"}),
				strmangle.WhereClause("\"", "\"", 2, wingsEcnTransactionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ActionLogRefID = o.ID
		}
	}

	if o.R == nil {
		o.R = &wingsEcnActionLogR{
			ActionLogRefWingsEcnTransactions: related,
		}
	} else {
		o.R.ActionLogRefWingsEcnTransactions = append(o.R.ActionLogRefWingsEcnTransactions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &wingsEcnTransactionR{
				ActionLogRef: o,
			}
		} else {
			rel.R.ActionLogRef = o
		}
	}
	return nil
}

// WingsEcnActionLogs retrieves all the records using an executor.
func WingsEcnActionLogs(mods ...qm.QueryMod) wingsEcnActionLogQuery {
	mods = append(mods, qm.From("\"wings_ecn_action_log\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"wings_ecn_action_log\".*"})
	}

	return wingsEcnActionLogQuery{q}
}

// FindWingsEcnActionLog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWingsEcnActionLog(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WingsEcnActionLog, error) {
	wingsEcnActionLogObj := &WingsEcnActionLog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"wings_ecn_action_log\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, wingsEcnActionLogObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from wings_ecn_action_log")
	}

	if err = wingsEcnActionLogObj.doAfterSelectHooks(ctx, exec); err != nil {
		return wingsEcnActionLogObj, err
	}

	return wingsEcnActionLogObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WingsEcnActionLog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no wings_ecn_action_log provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(wingsEcnActionLogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	wingsEcnActionLogInsertCacheMut.RLock()
	cache, cached := wingsEcnActionLogInsertCache[key]
	wingsEcnActionLogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			wingsEcnActionLogAllColumns,
			wingsEcnActionLogColumnsWithDefault,
			wingsEcnActionLogColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(wingsEcnActionLogType, wingsEcnActionLogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(wingsEcnActionLogType, wingsEcnActionLogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"wings_ecn_action_log\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"wings_ecn_action_log\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into wings_ecn_action_log")
	}

	if !cached {
		wingsEcnActionLogInsertCacheMut.Lock()
		wingsEcnActionLogInsertCache[key] = cache
		wingsEcnActionLogInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WingsEcnActionLog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WingsEcnActionLog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	wingsEcnActionLogUpdateCacheMut.RLock()
	cache, cached := wingsEcnActionLogUpdateCache[key]
	wingsEcnActionLogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			wingsEcnActionLogAllColumns,
			wingsEcnActionLogPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update wings_ecn_action_log, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"wings_ecn_action_log\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, wingsEcnActionLogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(wingsEcnActionLogType, wingsEcnActionLogMapping, append(wl, wingsEcnActionLogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update wings_ecn_action_log row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for wings_ecn_action_log")
	}

	if !cached {
		wingsEcnActionLogUpdateCacheMut.Lock()
		wingsEcnActionLogUpdateCache[key] = cache
		wingsEcnActionLogUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q wingsEcnActionLogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for wings_ecn_action_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for wings_ecn_action_log")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WingsEcnActionLogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wingsEcnActionLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"wings_ecn_action_log\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, wingsEcnActionLogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in wingsEcnActionLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all wingsEcnActionLog")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WingsEcnActionLog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no wings_ecn_action_log provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(wingsEcnActionLogColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	wingsEcnActionLogUpsertCacheMut.RLock()
	cache, cached := wingsEcnActionLogUpsertCache[key]
	wingsEcnActionLogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			wingsEcnActionLogAllColumns,
			wingsEcnActionLogColumnsWithDefault,
			wingsEcnActionLogColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			wingsEcnActionLogAllColumns,
			wingsEcnActionLogPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert wings_ecn_action_log, could not build update column list")
		}

		ret := strmangle.SetComplement(wingsEcnActionLogAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(wingsEcnActionLogPrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert wings_ecn_action_log, could not build conflict column list")
			}

			conflict = make([]string, len(wingsEcnActionLogPrimaryKeyColumns))
			copy(conflict, wingsEcnActionLogPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"wings_ecn_action_log\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(wingsEcnActionLogType, wingsEcnActionLogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(wingsEcnActionLogType, wingsEcnActionLogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert wings_ecn_action_log")
	}

	if !cached {
		wingsEcnActionLogUpsertCacheMut.Lock()
		wingsEcnActionLogUpsertCache[key] = cache
		wingsEcnActionLogUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WingsEcnActionLog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WingsEcnActionLog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no WingsEcnActionLog provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), wingsEcnActionLogPrimaryKeyMapping)
	sql := "DELETE FROM \"wings_ecn_action_log\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from wings_ecn_action_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for wings_ecn_action_log")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q wingsEcnActionLogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no wingsEcnActionLogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from wings_ecn_action_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for wings_ecn_action_log")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WingsEcnActionLogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(wingsEcnActionLogBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wingsEcnActionLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"wings_ecn_action_log\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, wingsEcnActionLogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from wingsEcnActionLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for wings_ecn_action_log")
	}

	if len(wingsEcnActionLogAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WingsEcnActionLog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWingsEcnActionLog(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WingsEcnActionLogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WingsEcnActionLogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wingsEcnActionLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"wings_ecn_action_log\".* FROM \"wings_ecn_action_log\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, wingsEcnActionLogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in WingsEcnActionLogSlice")
	}

	*o = slice

	return nil
}

// WingsEcnActionLogExists checks if the WingsEcnActionLog row exists.
func WingsEcnActionLogExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"wings_ecn_action_log\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if wings_ecn_action_log exists")
	}

	return exists, nil
}

// Exists checks if the WingsEcnActionLog row exists.
func (o *WingsEcnActionLog) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WingsEcnActionLogExists(ctx, exec, o.ID)
}
