// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package pgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WingsEcnUserTotal is an object representing the database table.
type WingsEcnUserTotal struct {
	ID                  string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserRefID           string    `boil:"user_ref_id" json:"user_ref_id" toml:"user_ref_id" yaml:"user_ref_id"`
	TotalWings          int       `boil:"total_wings" json:"total_wings" toml:"total_wings" yaml:"total_wings"`
	CounterSentMessages int       `boil:"counter_sent_messages" json:"counter_sent_messages" toml:"counter_sent_messages" yaml:"counter_sent_messages"`
	CounterDailyCheckIn int       `boil:"counter_daily_check_in" json:"counter_daily_check_in" toml:"counter_daily_check_in" yaml:"counter_daily_check_in"`
	PremiumExpiresIn    null.Time `boil:"premium_expires_in" json:"premium_expires_in,omitempty" toml:"premium_expires_in" yaml:"premium_expires_in,omitempty"`
	IsActive            null.Int  `boil:"is_active" json:"is_active,omitempty" toml:"is_active" yaml:"is_active,omitempty"`
	CreatedBy           null.Int  `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	CreatedDate         null.Time `boil:"created_date" json:"created_date,omitempty" toml:"created_date" yaml:"created_date,omitempty"`
	LastUpdated         null.Time `boil:"last_updated" json:"last_updated,omitempty" toml:"last_updated" yaml:"last_updated,omitempty"`
	UpdatedBy           null.Int  `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`
	// Date of last successful check-in (UTC date only)
	StreakLastDate null.Time `boil:"streak_last_date" json:"streak_last_date,omitempty" toml:"streak_last_date" yaml:"streak_last_date,omitempty"`
	// Current consecutive check-in streak
	StreakCurrentDays int `boil:"streak_current_days" json:"streak_current_days" toml:"streak_current_days" yaml:"streak_current_days"`
	// Longest streak ever achieved by user
	StreakLongestDays int `boil:"streak_longest_days" json:"streak_longest_days" toml:"streak_longest_days" yaml:"streak_longest_days"`

	R *wingsEcnUserTotalR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L wingsEcnUserTotalL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WingsEcnUserTotalColumns = struct {
	ID                  string
	UserRefID           string
	TotalWings          string
	CounterSentMessages string
	CounterDailyCheckIn string
	PremiumExpiresIn    string
	IsActive            string
	CreatedBy           string
	CreatedDate         string
	LastUpdated         string
	UpdatedBy           string
	StreakLastDate      string
	StreakCurrentDays   string
	StreakLongestDays   string
}{
	ID:                  "id",
	UserRefID:           "user_ref_id",
	TotalWings:          "total_wings",
	CounterSentMessages: "counter_sent_messages",
	CounterDailyCheckIn: "counter_daily_check_in",
	PremiumExpiresIn:    "premium_expires_in",
	IsActive:            "is_active",
	CreatedBy:           "created_by",
	CreatedDate:         "created_date",
	LastUpdated:         "last_updated",
	UpdatedBy:           "updated_by",
	StreakLastDate:      "streak_last_date",
	StreakCurrentDays:   "streak_current_days",
	StreakLongestDays:   "streak_longest_days",
}

var WingsEcnUserTotalTableColumns = struct {
	ID                  string
	UserRefID           string
	TotalWings          string
	CounterSentMessages string
	CounterDailyCheckIn string
	PremiumExpiresIn    string
	IsActive            string
	CreatedBy           string
	CreatedDate         string
	LastUpdated         string
	UpdatedBy           string
	StreakLastDate      string
	StreakCurrentDays   string
	StreakLongestDays   string
}{
	ID:                  "wings_ecn_user_totals.id",
	UserRefID:           "wings_ecn_user_totals.user_ref_id",
	TotalWings:          "wings_ecn_user_totals.total_wings",
	CounterSentMessages: "wings_ecn_user_totals.counter_sent_messages",
	CounterDailyCheckIn: "wings_ecn_user_totals.counter_daily_check_in",
	PremiumExpiresIn:    "wings_ecn_user_totals.premium_expires_in",
	IsActive:            "wings_ecn_user_totals.is_active",
	CreatedBy:           "wings_ecn_user_totals.created_by",
	CreatedDate:         "wings_ecn_user_totals.created_date",
	LastUpdated:         "wings_ecn_user_totals.last_updated",
	UpdatedBy:           "wings_ecn_user_totals.updated_by",
	StreakLastDate:      "wings_ecn_user_totals.streak_last_date",
	StreakCurrentDays:   "wings_ecn_user_totals.streak_current_days",
	StreakLongestDays:   "wings_ecn_user_totals.streak_longest_days",
}

// Generated where

var WingsEcnUserTotalWhere = struct {
	ID                  whereHelperstring
	UserRefID           whereHelperstring
	TotalWings          whereHelperint
	CounterSentMessages whereHelperint
	CounterDailyCheckIn whereHelperint
	PremiumExpiresIn    whereHelpernull_Time
	IsActive            whereHelpernull_Int
	CreatedBy           whereHelpernull_Int
	CreatedDate         whereHelpernull_Time
	LastUpdated         whereHelpernull_Time
	UpdatedBy           whereHelpernull_Int
	StreakLastDate      whereHelpernull_Time
	StreakCurrentDays   whereHelperint
	StreakLongestDays   whereHelperint
}{
	ID:                  whereHelperstring{field: "\"wings_ecn_user_totals\".\"id\""},
	UserRefID:           whereHelperstring{field: "\"wings_ecn_user_totals\".\"user_ref_id\""},
	TotalWings:          whereHelperint{field: "\"wings_ecn_user_totals\".\"total_wings\""},
	CounterSentMessages: whereHelperint{field: "\"wings_ecn_user_totals\".\"counter_sent_messages\""},
	CounterDailyCheckIn: whereHelperint{field: "\"wings_ecn_user_totals\".\"counter_daily_check_in\""},
	PremiumExpiresIn:    whereHelpernull_Time{field: "\"wings_ecn_user_totals\".\"premium_expires_in\""},
	IsActive:            whereHelpernull_Int{field: "\"wings_ecn_user_totals\".\"is_active\""},
	CreatedBy:           whereHelpernull_Int{field: "\"wings_ecn_user_totals\".\"created_by\""},
	CreatedDate:         whereHelpernull_Time{field: "\"wings_ecn_user_totals\".\"created_date\""},
	LastUpdated:         whereHelpernull_Time{field: "\"wings_ecn_user_totals\".\"last_updated\""},
	UpdatedBy:           whereHelpernull_Int{field: "\"wings_ecn_user_totals\".\"updated_by\""},
	StreakLastDate:      whereHelpernull_Time{field: "\"wings_ecn_user_totals\".\"streak_last_date\""},
	StreakCurrentDays:   whereHelperint{field: "\"wings_ecn_user_totals\".\"streak_current_days\""},
	StreakLongestDays:   whereHelperint{field: "\"wings_ecn_user_totals\".\"streak_longest_days\""},
}

// WingsEcnUserTotalRels is where relationship names are stored.
var WingsEcnUserTotalRels = struct {
	UserRef string
}{
	UserRef: "UserRef",
}

// wingsEcnUserTotalR is where relationships are stored.
type wingsEcnUserTotalR struct {
	UserRef *User `boil:"UserRef" json:"UserRef" toml:"UserRef" yaml:"UserRef"`
}

// NewStruct creates a new relationship struct
func (*wingsEcnUserTotalR) NewStruct() *wingsEcnUserTotalR {
	return &wingsEcnUserTotalR{}
}

func (o *WingsEcnUserTotal) GetUserRef() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUserRef()
}

func (r *wingsEcnUserTotalR) GetUserRef() *User {
	if r == nil {
		return nil
	}

	return r.UserRef
}

// wingsEcnUserTotalL is where Load methods for each relationship are stored.
type wingsEcnUserTotalL struct{}

var (
	wingsEcnUserTotalAllColumns            = []string{"id", "user_ref_id", "total_wings", "counter_sent_messages", "counter_daily_check_in", "premium_expires_in", "is_active", "created_by", "created_date", "last_updated", "updated_by", "streak_last_date", "streak_current_days", "streak_longest_days"}
	wingsEcnUserTotalColumnsWithoutDefault = []string{"user_ref_id"}
	wingsEcnUserTotalColumnsWithDefault    = []string{"id", "total_wings", "counter_sent_messages", "counter_daily_check_in", "premium_expires_in", "is_active", "created_by", "created_date", "last_updated", "updated_by", "streak_last_date", "streak_current_days", "streak_longest_days"}
	wingsEcnUserTotalPrimaryKeyColumns     = []string{"id"}
	wingsEcnUserTotalGeneratedColumns      = []string{}
)

type (
	// WingsEcnUserTotalSlice is an alias for a slice of pointers to WingsEcnUserTotal.
	// This should almost always be used instead of []WingsEcnUserTotal.
	WingsEcnUserTotalSlice []*WingsEcnUserTotal
	// WingsEcnUserTotalHook is the signature for custom WingsEcnUserTotal hook methods
	WingsEcnUserTotalHook func(context.Context, boil.ContextExecutor, *WingsEcnUserTotal) error

	wingsEcnUserTotalQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	wingsEcnUserTotalType                 = reflect.TypeOf(&WingsEcnUserTotal{})
	wingsEcnUserTotalMapping              = queries.MakeStructMapping(wingsEcnUserTotalType)
	wingsEcnUserTotalPrimaryKeyMapping, _ = queries.BindMapping(wingsEcnUserTotalType, wingsEcnUserTotalMapping, wingsEcnUserTotalPrimaryKeyColumns)
	wingsEcnUserTotalInsertCacheMut       sync.RWMutex
	wingsEcnUserTotalInsertCache          = make(map[string]insertCache)
	wingsEcnUserTotalUpdateCacheMut       sync.RWMutex
	wingsEcnUserTotalUpdateCache          = make(map[string]updateCache)
	wingsEcnUserTotalUpsertCacheMut       sync.RWMutex
	wingsEcnUserTotalUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var wingsEcnUserTotalAfterSelectMu sync.Mutex
var wingsEcnUserTotalAfterSelectHooks []WingsEcnUserTotalHook

var wingsEcnUserTotalBeforeInsertMu sync.Mutex
var wingsEcnUserTotalBeforeInsertHooks []WingsEcnUserTotalHook
var wingsEcnUserTotalAfterInsertMu sync.Mutex
var wingsEcnUserTotalAfterInsertHooks []WingsEcnUserTotalHook

var wingsEcnUserTotalBeforeUpdateMu sync.Mutex
var wingsEcnUserTotalBeforeUpdateHooks []WingsEcnUserTotalHook
var wingsEcnUserTotalAfterUpdateMu sync.Mutex
var wingsEcnUserTotalAfterUpdateHooks []WingsEcnUserTotalHook

var wingsEcnUserTotalBeforeDeleteMu sync.Mutex
var wingsEcnUserTotalBeforeDeleteHooks []WingsEcnUserTotalHook
var wingsEcnUserTotalAfterDeleteMu sync.Mutex
var wingsEcnUserTotalAfterDeleteHooks []WingsEcnUserTotalHook

var wingsEcnUserTotalBeforeUpsertMu sync.Mutex
var wingsEcnUserTotalBeforeUpsertHooks []WingsEcnUserTotalHook
var wingsEcnUserTotalAfterUpsertMu sync.Mutex
var wingsEcnUserTotalAfterUpsertHooks []WingsEcnUserTotalHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WingsEcnUserTotal) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WingsEcnUserTotal) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WingsEcnUserTotal) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WingsEcnUserTotal) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WingsEcnUserTotal) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WingsEcnUserTotal) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WingsEcnUserTotal) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WingsEcnUserTotal) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WingsEcnUserTotal) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wingsEcnUserTotalAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWingsEcnUserTotalHook registers your hook function for all future operations.
func AddWingsEcnUserTotalHook(hookPoint boil.HookPoint, wingsEcnUserTotalHook WingsEcnUserTotalHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		wingsEcnUserTotalAfterSelectMu.Lock()
		wingsEcnUserTotalAfterSelectHooks = append(wingsEcnUserTotalAfterSelectHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		wingsEcnUserTotalBeforeInsertMu.Lock()
		wingsEcnUserTotalBeforeInsertHooks = append(wingsEcnUserTotalBeforeInsertHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		wingsEcnUserTotalAfterInsertMu.Lock()
		wingsEcnUserTotalAfterInsertHooks = append(wingsEcnUserTotalAfterInsertHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		wingsEcnUserTotalBeforeUpdateMu.Lock()
		wingsEcnUserTotalBeforeUpdateHooks = append(wingsEcnUserTotalBeforeUpdateHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		wingsEcnUserTotalAfterUpdateMu.Lock()
		wingsEcnUserTotalAfterUpdateHooks = append(wingsEcnUserTotalAfterUpdateHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		wingsEcnUserTotalBeforeDeleteMu.Lock()
		wingsEcnUserTotalBeforeDeleteHooks = append(wingsEcnUserTotalBeforeDeleteHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		wingsEcnUserTotalAfterDeleteMu.Lock()
		wingsEcnUserTotalAfterDeleteHooks = append(wingsEcnUserTotalAfterDeleteHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		wingsEcnUserTotalBeforeUpsertMu.Lock()
		wingsEcnUserTotalBeforeUpsertHooks = append(wingsEcnUserTotalBeforeUpsertHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		wingsEcnUserTotalAfterUpsertMu.Lock()
		wingsEcnUserTotalAfterUpsertHooks = append(wingsEcnUserTotalAfterUpsertHooks, wingsEcnUserTotalHook)
		wingsEcnUserTotalAfterUpsertMu.Unlock()
	}
}

// One returns a single wingsEcnUserTotal record from the query.
func (q wingsEcnUserTotalQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WingsEcnUserTotal, error) {
	o := &WingsEcnUserTotal{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: failed to execute a one query for wings_ecn_user_totals")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WingsEcnUserTotal records from the query.
func (q wingsEcnUserTotalQuery) All(ctx context.Context, exec boil.ContextExecutor) (WingsEcnUserTotalSlice, error) {
	var o []*WingsEcnUserTotal

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "pgmodel: failed to assign all query results to WingsEcnUserTotal slice")
	}

	if len(wingsEcnUserTotalAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WingsEcnUserTotal records in the query.
func (q wingsEcnUserTotalQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to count wings_ecn_user_totals rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q wingsEcnUserTotalQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: failed to check if wings_ecn_user_totals exists")
	}

	return count > 0, nil
}

// UserRef pointed to by the foreign key.
func (o *WingsEcnUserTotal) UserRef(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserRefID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUserRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (wingsEcnUserTotalL) LoadUserRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWingsEcnUserTotal interface{}, mods queries.Applicator) error {
	var slice []*WingsEcnUserTotal
	var object *WingsEcnUserTotal

	if singular {
		var ok bool
		object, ok = maybeWingsEcnUserTotal.(*WingsEcnUserTotal)
		if !ok {
			object = new(WingsEcnUserTotal)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWingsEcnUserTotal)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWingsEcnUserTotal))
			}
		}
	} else {
		s, ok := maybeWingsEcnUserTotal.(*[]*WingsEcnUserTotal)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWingsEcnUserTotal)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWingsEcnUserTotal))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &wingsEcnUserTotalR{}
		}
		args[object.UserRefID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &wingsEcnUserTotalR{}
			}

			args[obj.UserRefID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UserRef = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserRefWingsEcnUserTotal = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserRefID == foreign.ID {
				local.R.UserRef = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserRefWingsEcnUserTotal = local
				break
			}
		}
	}

	return nil
}

// SetUserRef of the wingsEcnUserTotal to the related item.
// Sets o.R.UserRef to related.
// Adds o to related.R.UserRefWingsEcnUserTotal.
func (o *WingsEcnUserTotal) SetUserRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"wings_ecn_user_totals\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_ref_id"}),
		strmangle.WhereClause("\"", "\"", 2, wingsEcnUserTotalPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserRefID = related.ID
	if o.R == nil {
		o.R = &wingsEcnUserTotalR{
			UserRef: related,
		}
	} else {
		o.R.UserRef = related
	}

	if related.R == nil {
		related.R = &userR{
			UserRefWingsEcnUserTotal: o,
		}
	} else {
		related.R.UserRefWingsEcnUserTotal = o
	}

	return nil
}

// WingsEcnUserTotals retrieves all the records using an executor.
func WingsEcnUserTotals(mods ...qm.QueryMod) wingsEcnUserTotalQuery {
	mods = append(mods, qm.From("\"wings_ecn_user_totals\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"wings_ecn_user_totals\".*"})
	}

	return wingsEcnUserTotalQuery{q}
}

// FindWingsEcnUserTotal retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWingsEcnUserTotal(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WingsEcnUserTotal, error) {
	wingsEcnUserTotalObj := &WingsEcnUserTotal{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"wings_ecn_user_totals\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, wingsEcnUserTotalObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "pgmodel: unable to select from wings_ecn_user_totals")
	}

	if err = wingsEcnUserTotalObj.doAfterSelectHooks(ctx, exec); err != nil {
		return wingsEcnUserTotalObj, err
	}

	return wingsEcnUserTotalObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WingsEcnUserTotal) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("pgmodel: no wings_ecn_user_totals provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(wingsEcnUserTotalColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	wingsEcnUserTotalInsertCacheMut.RLock()
	cache, cached := wingsEcnUserTotalInsertCache[key]
	wingsEcnUserTotalInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			wingsEcnUserTotalAllColumns,
			wingsEcnUserTotalColumnsWithDefault,
			wingsEcnUserTotalColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(wingsEcnUserTotalType, wingsEcnUserTotalMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(wingsEcnUserTotalType, wingsEcnUserTotalMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"wings_ecn_user_totals\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"wings_ecn_user_totals\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to insert into wings_ecn_user_totals")
	}

	if !cached {
		wingsEcnUserTotalInsertCacheMut.Lock()
		wingsEcnUserTotalInsertCache[key] = cache
		wingsEcnUserTotalInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WingsEcnUserTotal.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WingsEcnUserTotal) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	wingsEcnUserTotalUpdateCacheMut.RLock()
	cache, cached := wingsEcnUserTotalUpdateCache[key]
	wingsEcnUserTotalUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			wingsEcnUserTotalAllColumns,
			wingsEcnUserTotalPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("pgmodel: unable to update wings_ecn_user_totals, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"wings_ecn_user_totals\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, wingsEcnUserTotalPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(wingsEcnUserTotalType, wingsEcnUserTotalMapping, append(wl, wingsEcnUserTotalPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update wings_ecn_user_totals row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by update for wings_ecn_user_totals")
	}

	if !cached {
		wingsEcnUserTotalUpdateCacheMut.Lock()
		wingsEcnUserTotalUpdateCache[key] = cache
		wingsEcnUserTotalUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q wingsEcnUserTotalQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all for wings_ecn_user_totals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected for wings_ecn_user_totals")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WingsEcnUserTotalSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("pgmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wingsEcnUserTotalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"wings_ecn_user_totals\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, wingsEcnUserTotalPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to update all in wingsEcnUserTotal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to retrieve rows affected all in update all wingsEcnUserTotal")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WingsEcnUserTotal) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("pgmodel: no wings_ecn_user_totals provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(wingsEcnUserTotalColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	wingsEcnUserTotalUpsertCacheMut.RLock()
	cache, cached := wingsEcnUserTotalUpsertCache[key]
	wingsEcnUserTotalUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			wingsEcnUserTotalAllColumns,
			wingsEcnUserTotalColumnsWithDefault,
			wingsEcnUserTotalColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			wingsEcnUserTotalAllColumns,
			wingsEcnUserTotalPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("pgmodel: unable to upsert wings_ecn_user_totals, could not build update column list")
		}

		ret := strmangle.SetComplement(wingsEcnUserTotalAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(wingsEcnUserTotalPrimaryKeyColumns) == 0 {
				return errors.New("pgmodel: unable to upsert wings_ecn_user_totals, could not build conflict column list")
			}

			conflict = make([]string, len(wingsEcnUserTotalPrimaryKeyColumns))
			copy(conflict, wingsEcnUserTotalPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"wings_ecn_user_totals\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(wingsEcnUserTotalType, wingsEcnUserTotalMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(wingsEcnUserTotalType, wingsEcnUserTotalMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to upsert wings_ecn_user_totals")
	}

	if !cached {
		wingsEcnUserTotalUpsertCacheMut.Lock()
		wingsEcnUserTotalUpsertCache[key] = cache
		wingsEcnUserTotalUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WingsEcnUserTotal record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WingsEcnUserTotal) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("pgmodel: no WingsEcnUserTotal provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), wingsEcnUserTotalPrimaryKeyMapping)
	sql := "DELETE FROM \"wings_ecn_user_totals\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete from wings_ecn_user_totals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by delete for wings_ecn_user_totals")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q wingsEcnUserTotalQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("pgmodel: no wingsEcnUserTotalQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from wings_ecn_user_totals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for wings_ecn_user_totals")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WingsEcnUserTotalSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(wingsEcnUserTotalBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wingsEcnUserTotalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"wings_ecn_user_totals\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, wingsEcnUserTotalPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: unable to delete all from wingsEcnUserTotal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "pgmodel: failed to get rows affected by deleteall for wings_ecn_user_totals")
	}

	if len(wingsEcnUserTotalAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WingsEcnUserTotal) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWingsEcnUserTotal(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WingsEcnUserTotalSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WingsEcnUserTotalSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wingsEcnUserTotalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"wings_ecn_user_totals\".* FROM \"wings_ecn_user_totals\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, wingsEcnUserTotalPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "pgmodel: unable to reload all in WingsEcnUserTotalSlice")
	}

	*o = slice

	return nil
}

// WingsEcnUserTotalExists checks if the WingsEcnUserTotal row exists.
func WingsEcnUserTotalExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"wings_ecn_user_totals\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "pgmodel: unable to check if wings_ecn_user_totals exists")
	}

	return exists, nil
}

// Exists checks if the WingsEcnUserTotal row exists.
func (o *WingsEcnUserTotal) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WingsEcnUserTotalExists(ctx, exec, o.ID)
}
